// A matching geometric reference: bounded analytic ray tracing, not a PT reference.
// Twelve dielectric/mirror events; environment + direct diffuse surfaces. Photon
// overlays remain X-ray diagnostics, deliberately not occluded by this backdrop.
export function makeReference(canvas){const gl=canvas.getContext('webgl2',{alpha:false,antialias:false});if(!gl)throw Error('Reference needs WebGL2');
const vs=`#version 300 es
out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0,1);}`;
const fs=`#version 300 es
precision highp float;in vec2 uv;out vec4 outColor;uniform vec3 eye,forward,right,up,bounds,light;uniform vec2 resolution;uniform vec4 spheres[3],panels[2];uniform vec2 halfPanel[2];uniform int sphereCount,panelCount;uniform bool sticker;uniform float brightness,ior;uniform int editedObject,objectMaterial;
float sph(vec3 o,vec3 d,vec4 s){vec3 q=o-s.xyz;float b=dot(q,d),h=b*b-dot(q,q)+s.w*s.w;if(h<0.)return 1e6;float a=-b-sqrt(h),z=-b+sqrt(h);return a>.0002?a:z>.0002?z:1e6;}
float hit(vec3 o,vec3 d,out vec3 n,out int id){float t=1e6;id=-1;n=vec3(0,1,0);for(int i=0;i<3;i++){if(i>=sphereCount)break;float h=sph(o,d,spheres[i]);if(h<t){t=h;id=i;n=normalize(o+d*h-spheres[i].xyz);}}
for(int i=0;i<2;i++){if(i>=panelCount)break;vec3 nn=vec3(cos(panels[i].w),sin(panels[i].w),0),u=vec3(-nn.y,nn.x,0);float den=dot(d,nn);if(abs(den)<.00001)continue;float h=dot(panels[i].xyz-o,nn)/den;vec3 q=o+d*h-panels[i].xyz;if(h>.0002&&h<t&&abs(dot(q,u))<halfPanel[i].x&&abs(q.z)<halfPanel[i].y){t=h;id=3+i;n=den<0.?nn:-nn;}}
for(int a=0;a<3;a++)for(int s=-1;s<=1;s+=2){if(a==2&&s==1||abs(d[a])<.00001)continue;float h=(float(s)*bounds[a]-o[a])/d[a];vec3 p=o+d*h;if(h>.0002&&h<t&&abs(p[(a+1)%3])<=bounds[(a+1)%3]&&abs(p[(a+2)%3])<=bounds[(a+2)%3]){t=h;id=5+a*2+(s+1)/2;n=vec3(0);n[a]=-float(s);}}return t;}
vec3 env(vec3 d){return mix(vec3(.015,.027,.05),vec3(.23,.32,.38),d.y*.5+.5)+vec3(1.3,1.15,.8)*pow(max(0.,dot(d,normalize(vec3(-.4,1.,.6)))),65.);}
vec3 wall(vec3 p,vec3 n,int id,vec3 d){vec3 base=id==5?vec3(.30,.08,.035):id==6?vec3(.04,.24,.20):vec3(.26,.31,.34);if(id==7){base*=.82+.18*mod(floor(p.x*4.)+floor(p.z*4.),2.);if(sticker&&length((p.xz-vec2(.2,.38))/vec2(.60,.45))<1.){float f=dot(reflect(d,n),normalize(light-p));base=.28+.24*cos(vec3(0,2.1,4.2)+f*13.+length(p.xz)*8.);}}vec3 L=light-p;float nd=max(0.,dot(n,normalize(L)));return base*(.3+nd*3./max(1.,dot(L,L)));}
void main(){vec2 q=uv*2.-1.;q.x*=resolution.x/resolution.y;vec3 d=normalize(forward+tan(.5)*(right*q.x+up*q.y)),o=eye,c=vec3(0),w=vec3(1);for(int bounce=0;bounce<12;bounce++){vec3 n;int id;float t=hit(o,d,n,id);if(id<0){c+=w*env(d)*(bounce==0?.055:1.);break;}vec3 p=o+d*t;if(id>=5){c+=w*wall(p,n,id,d);break;}if(id==editedObject&&objectMaterial==2){c+=w*vec3(.36,.29,.16)*(.18+max(0.,dot(n,normalize(light-p))));break;}if(id>=3||(id==editedObject&&objectMaterial==1)){d=reflect(d,n);w*=id==3?vec3(.92):vec3(.40,.85,.95);}else{bool entering=dot(d,n)<0.;n=entering?n:-n;float f0=pow((ior-1.)/(ior+1.),2.);float F=f0+(1.-f0)*pow(1.-max(0.,-dot(d,n)),5.);vec3 next=refract(d,n,entering?1./ior:ior);if(length(next)<.1){d=reflect(d,n);}else{c+=w*F*env(reflect(d,n));w*=1.-F;d=next;}}o=p+d*.0005;}c*=brightness;outColor=vec4(pow(max(c,vec3(0))/(1.+max(c,vec3(0))),vec3(1./2.2)),1);}`;
const program=gl.createProgram();for(const [type,src]of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(program,s);gl.deleteShader(s);}gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));const u=k=>gl.getUniformLocation(program,k);
return {draw(cam,scene,sticker,brightness){gl.useProgram(program);gl.viewport(0,0,canvas.width,canvas.height);for(const [k,v]of Object.entries({eye:cam.eye,forward:cam.f,right:cam.r,up:cam.u,bounds:scene.bounds,light:scene.light}))gl.uniform3fv(u(k),v);gl.uniform2f(u('resolution'),canvas.width,canvas.height);gl.uniform1i(u('sphereCount'),scene.spheres.length);gl.uniform1i(u('panelCount'),scene.panels.length);gl.uniform1i(u('sticker'),sticker);gl.uniform1f(u('brightness'),brightness);gl.uniform1f(u('ior'),scene.ior||1.5);gl.uniform1i(u('editedObject'),scene.editedObject??-1);gl.uniform1i(u('objectMaterial'),scene.material==='mirror'?1:scene.material==='diffuse'?2:0);scene.spheres.forEach((s,i)=>gl.uniform4fv(u('spheres['+i+']'),s));scene.panels.forEach((p,i)=>{gl.uniform4fv(u('panels['+i+']'),[...p.c,p.angle]);gl.uniform2fv(u('halfPanel['+i+']'),p.half);});gl.drawArrays(gl.TRIANGLES,0,3);},dispose(){gl.deleteProgram(program);}};
}
