import * as THREE from 'three';
import { Simulation } from '../core/Simulation.js';
import { registerSim } from '../core/registry.js';
import { piDigitsHTML } from './wedgeUnfold.js';

// Same rescale as GaltonBoardPi/UniformSumE: main.js advances 1e-4 sim-seconds
// per step(), so one board-second is ~one wall second at speed 1 / 60 fps.
const TIME_SCALE = 16.7;
const DT_SUB = 0.004;           // substep (board-seconds). Movement v·dt = 0.004 << r, no tunnelling.
const TURBO_SUBSTEPS = 260;     // extra invisible substeps per step() call — fast-forwards the SAME gas
const MAX_SUBSTEPS = 4000;      // safety clamp per step() call

const NMIN = 12, NMAX = 60;
const BALL_R = 0.02;            // ball radius in unit-box coords (dilute: packing ≈ N·π·r²)
const V0 = 1;                   // initial speed (random direction) — energy is conserved thereafter
const WMIN = 0.015, WMAX = 0.06;

const KMAX = 8;                 // histogram bins 0..KMAX (P(k>8) at λ~1.5 is ~1e-5)
const FLASH_DUR = 0.09;         // board-seconds a ball stays lit after a collision

// --- scene layout (ortho) ---
const BOX_X0 = -1.05, BOX_X1 = -0.15;      // gas box (square in screen)
const BOX_Y0 = -0.40, BOX_Y1 = 0.50;
const BOX_W = BOX_X1 - BOX_X0;             // 0.90
const BAR_Y0 = -0.56, BAR_Y1 = -0.50;      // window-timer bar under the box

const HIST_X0 = 0.06, HIST_DX = 0.118;
const HIST_FLOOR = -0.40, BAR_MAX_H = 0.9;

const C_BALL = 0x4cc9f0, C_FLASH = 0xf7c948;
const C_EMPTY = 0xf7c948, C_BAR = 0x4cc9f0;

export class CollisionGasE extends Simulation {
  static id = 'collision-gas-e';
  static title = 'Collision Gas — e from Poisson counting';
  static description = 'Count elastic collisions of a real 2D gas in fixed time windows; the empty-window fraction is e^(−λ), so e falls out';
  static piMechanism = 'statistical: a dilute gas of many independent ball-pairs makes the collision stream Poisson (superposition), so windows with 0 collisions have probability e^(−λ) ⇒ e = (1/f₀)^(1/λ̄)';
  static rigor = 'Statistical';
  static sortOrder = 208;
  static piNature = 'statistical';
  static piLabel = 'e ≈';
  static previewSteps = 60;
  static alternatives = [
    { id: 'uniform-sum-e', label: 'e from random pours' },
    { id: 'derangement-e', label: 'e from shuffles' },
    { id: 'draining-vessel-e', label: 'e from a decay' },
  ];
  static explanation = {
    setup: 'N balls bounce elastically in a 2D box — every ball–ball and ball–wall bounce conserves momentum and energy exactly. Only the ball–ball collisions are counted: each one is a genuine physical event. Time is sliced into equal windows of duration W, and for each window we record k, the number of collisions that happened in it. Nothing about e is fed in — the balls start from uniform-random positions and uniform-random velocity directions, and the hard-disk dynamics are chaotic.',
    insight: 'A single pair of balls collides on a roughly renewal schedule, but the box holds ~N(N−1)/2 pairs colliding on their own incommensurate clocks. Superposing that many sparse, near-independent event streams drives the aggregate toward a Poisson process (the Palm–Khinchin / superposition theorem) — and it gets MORE Poisson as N grows. For a Poisson stream of mean λ per window, P(k collisions) = e^(−λ)·λ^k/k!, so the fraction of EMPTY windows is P(0) = e^(−λ). Measure that fraction f₀ and the mean λ̄, and invert: e = (1/f₀)^(1/λ̄). Both numbers are measured off the collision counts — e is never assumed, exactly as Buffon’s uniform needles hand back π.',
    contrast: 'This is the collisional cousin of the random pours and the shuffles: the same "independent random events are Poisson, and empty outcomes carry e^(−λ)" idea, but generated by honest Newtonian billiards instead of a random-number call. Why is there no EXACT collision-e the way there is an exact collision-π? Elastic energy conservation is a circle in velocity space — |v| fixed — so collision COUNTS (Galperin’s two blocks) hand back π. e is not geometric; it needs the exponential/rare-event structure of independent random timings, which the gas only approaches in the dilute, many-body, chaotic limit.',
    formula: 'e ≈ (1/f₀)^(1/λ̄),   f₀ = empty windows / total windows,   λ̄ = mean collisions / window   [STATISTICAL]',
    getExpected: (params) => {
      const n = params.n || 40;
      const pack = (n * Math.PI * BALL_R * BALL_R * 100).toFixed(1);
      return `With N=${n} balls of radius ${BALL_R} in a unit box the packing fraction is ~${pack}% — dilute, so collisions are nearly independent and the per-window count is close to Poisson(λ̄). The empty-window estimator e = (1/f₀)^(1/λ̄) is consistent: it converges to e = 2.71828… as windows accumulate, the residual bias shrinking as the gas is made more dilute (smaller balls, more balls). Expect within ~1–2% of e after ~10⁴–10⁵ windows; the remaining error is finite-density correlation (sub-Poisson bias) plus 1/√N Monte-Carlo noise. Turbo fast-forwards the same gas so windows pile up quickly.`;
    }
  };

  constructor(params = {}) {
    super(params);
    this.n = Math.min(NMAX, Math.max(NMIN, params.n || 40));
    this.windowW = Math.min(WMAX, Math.max(WMIN, params.windowW || 0.0175));
    this.turbo = true;
    // Preallocated ball state (no per-frame / per-collision allocation).
    this.px = new Float32Array(NMAX);
    this.py = new Float32Array(NMAX);
    this.vx = new Float32Array(NMAX);
    this.vy = new Float32Array(NMAX);
    this.flash = new Float32Array(NMAX);   // board-clock time of last collision per ball
    // Poisson reference mass p[k] = e^{-λ} λ^k / k!, rebuilt from λ̄ each frame.
    this.poisProb = new Float64Array(KMAX + 1);
    this._mtx = new THREE.Matrix4();
    this._col = new THREE.Color();
    this.reset();
  }

  reset() {
    super.reset();
    this.boardClock = 0;
    this.subCarry = 0;
    // Window / Poisson statistics.
    this.winClock = 0;           // time elapsed in the current (open) window
    this.winK = 0;               // collisions counted in the current window
    this.winCount = 0;           // closed windows
    this.emptyCount = 0;         // windows with k = 0
    this.totalColl = 0;          // total collisions across closed windows
    this.winHist = new Int32Array(KMAX + 1);
    this.nextMilestone = 1;
    this.collisionCount = 0;
    this._seedGas();
  }

  // Uniform-random start: jittered non-overlapping grid, random velocity
  // directions at fixed speed. No e (or π) anywhere in the initial conditions.
  _seedGas() {
    const n = this.n;
    const cols = Math.ceil(Math.sqrt(n));
    const cell = 1 / cols;
    const margin = BALL_R + 0.01;
    let idx = 0;
    for (let gy = 0; gy < cols && idx < n; gy++) {
      for (let gx = 0; gx < cols && idx < n; gx++) {
        const jx = (Math.random() - 0.5) * (cell - 2 * margin);
        const jy = (Math.random() - 0.5) * (cell - 2 * margin);
        this.px[idx] = (gx + 0.5) * cell + jx;
        this.py[idx] = (gy + 0.5) * cell + jy;
        const a = Math.random() * Math.PI * 2;
        this.vx[idx] = Math.cos(a) * V0;
        this.vy[idx] = Math.sin(a) * V0;
        this.flash[idx] = -1;
        idx++;
      }
    }
  }

  getControls() {
    return [
      {
        type: 'slider', id: 'n', label: 'Balls N (more → more Poisson)', highlight: true,
        min: NMIN, max: NMAX, step: 2, default: this.n,
        onChange: (val) => { this.n = val; this.reset(); this.initSimScene(); }
      },
      {
        type: 'slider', id: 'windowW', label: 'Window W (sets λ)',
        min: WMIN, max: WMAX, step: 0.0025, default: this.windowW,
        onChange: (val) => { this.windowW = val; this.reset(); }
      },
      { type: 'toggle', id: 'turbo', label: 'Turbo (fast-forward the gas)', default: this.turbo },
      { type: 'slider', id: 'speed', label: 'Speed', min: 0.1, max: 20, step: 0.1, default: 1 },
    ];
  }

  getPhaseSpaceViews() {
    return [
      {
        id: 'convergence', label: 'log windows vs estimate error', dimension: 2,
        primary: true, boundary: 'none',
        axisLabels: { x: 'log10 windows', y: '(ê − e)/e' }
      }
    ];
  }

  step(dt) {
    const tb = dt * TIME_SCALE;
    this.subCarry += tb;
    let nsub = Math.floor(this.subCarry / DT_SUB);
    this.subCarry -= nsub * DT_SUB;
    if (this.turbo) nsub += TURBO_SUBSTEPS;
    if (nsub > MAX_SUBSTEPS) nsub = MAX_SUBSTEPS;

    let recorded = false;
    for (let s = 0; s < nsub; s++) {
      if (this._substep()) recorded = true;
    }

    this.collisionCount = this.winCount;
    if (this.winCount >= this.nextMilestone) {
      this.pendingPhasePoints.push([...this.getPhasePoint()]);
      this.nextMilestone = Math.max(this.winCount + 1, Math.ceil(this.winCount * 1.02));
    }
    return recorded;
  }

  // One fixed-dt substep of hard-disk dynamics + window bookkeeping.
  // Returns true when a window closes (a statistic was recorded).
  _substep() {
    const n = this.n, r = BALL_R, dt = DT_SUB, d2min = (2 * r) * (2 * r);
    this.boardClock += dt;

    // 1) drift + elastic wall reflections (walls conserve energy; not counted as events).
    for (let i = 0; i < n; i++) {
      let x = this.px[i] + this.vx[i] * dt;
      let y = this.py[i] + this.vy[i] * dt;
      if (x < r) { x = r; if (this.vx[i] < 0) this.vx[i] = -this.vx[i]; }
      else if (x > 1 - r) { x = 1 - r; if (this.vx[i] > 0) this.vx[i] = -this.vx[i]; }
      if (y < r) { y = r; if (this.vy[i] < 0) this.vy[i] = -this.vy[i]; }
      else if (y > 1 - r) { y = 1 - r; if (this.vy[i] > 0) this.vy[i] = -this.vy[i]; }
      this.px[i] = x; this.py[i] = y;
    }

    // 2) ball–ball elastic collisions (equal mass → swap the normal velocity
    //    component). Only resolved when overlapping AND approaching, so each
    //    physical collision is counted exactly once. O(N²), fine for N≤60.
    for (let i = 0; i < n; i++) {
      const xi = this.px[i], yi = this.py[i];
      for (let j = i + 1; j < n; j++) {
        const dx = this.px[j] - xi, dy = this.py[j] - yi;
        const d2 = dx * dx + dy * dy;
        if (d2 >= d2min || d2 < 1e-12) continue;
        const d = Math.sqrt(d2);
        const nx = dx / d, ny = dy / d;
        const dvx = this.vx[j] - this.vx[i], dvy = this.vy[j] - this.vy[i];
        const dvn = dvx * nx + dvy * ny;
        if (dvn >= 0) continue;                 // separating (or grazing) — no collision
        this.vx[i] += dvn * nx; this.vy[i] += dvn * ny;
        this.vx[j] -= dvn * nx; this.vy[j] -= dvn * ny;
        this.winK++;                            // one counted collision event
        this.flash[i] = this.boardClock;
        this.flash[j] = this.boardClock;
      }
    }

    // 3) window bookkeeping: close a window every W board-seconds.
    this.winClock += dt;
    if (this.winClock >= this.windowW) {
      this.winClock -= this.windowW;
      const k = this.winK;
      this.winHist[k > KMAX ? KMAX : k]++;
      this.totalColl += k;
      if (k === 0) this.emptyCount++;
      this.winCount++;
      this.winK = 0;
      return true;
    }
    return false;
  }

  _lambda() {
    return this.winCount > 0 ? this.totalColl / this.winCount : 0;
  }

  _f0() {
    return this.winCount > 0 ? this.emptyCount / this.winCount : 0;
  }

  getCountLabel() { return 'Windows'; }

  getPiApproximation() {
    const lam = this._lambda(), f0 = this._f0();
    if (lam <= 0 || f0 <= 0 || f0 >= 1) return 0;
    return Math.pow(1 / f0, 1 / lam);          // e = (1/f₀)^(1/λ̄) = f₀^(−1/λ̄)
  }

  getPiReadout() {
    const e = this.getPiApproximation();
    return e > 0 ? e.toFixed(6) : 'collecting…';
  }

  getFormulaHTML() {
    const e = this.getPiApproximation();
    const live = e > 0 ? piDigitsHTML(e, 4, Math.E) : 'collecting…';
    const lam = this._lambda(), f0 = this._f0();
    const lamStr = this.winCount > 0 ? lam.toFixed(3) : '—';
    const f0Str = this.winCount > 0 ? f0.toFixed(4) : '—';
    const eLamStr = this.winCount > 0 ? Math.exp(-lam).toFixed(4) : '—';
    return `
      <strong>empty-window fraction</strong>:
      independent random collisions are <span class="f-angle">Poisson(λ)</span>, so
      <span class="f-angle">P(0 in a window) = e^(−λ)</span><br>
      <span class="f-muted">measured f₀ = ${f0Str} vs e^(−λ̄) = ${eLamStr} &nbsp;·&nbsp; invert: e = (1/f₀)^(1/λ̄)</span><br>
      <span class="f-result">e</span> ≈
      (1/<span class="f-count">${f0Str}</span>)^(1/<span class="f-count">${lamStr}</span>)
      <br><span style="font-size:1.1em">e = ${live}</span>
      <br><span class="f-count">λ̄ = ${lamStr} collisions/window &nbsp;·&nbsp; ${this.winCount} windows &nbsp;·&nbsp; N = ${this.n}</span>
      <br><span class="f-muted">(target e = 2.71828…) Dilute-limit caveat: at finite packing the collision stream is slightly sub-Poisson, biasing e — smaller/more balls make it more independent, more Poisson.</span>
    `;
  }

  getPhasePoint() {
    const e = this.getPiApproximation();
    const x = Math.min(1, Math.max(-1, Math.log10(Math.max(this.winCount, 1)) / 6 * 2 - 1));
    const y = e > 0 ? Math.min(1, Math.max(-1, (e - Math.E) / Math.E * 8)) : 0;
    return [x, y];
  }

  getPhaseExtractor() { return (pt) => pt; }

  getPreviewBox() {
    return { x0: -1.12, x1: 1.12, y0: -0.66, y1: 0.74 };
  }

  // --- sim coords [0,1]² → screen box ---
  _sx(x) { return BOX_X0 + x * BOX_W; }
  _sy(y) { return BOX_Y0 + y * (BOX_Y1 - BOX_Y0); }

  _label(text, cx, cy, sx = 0.24, sy = 0.044, color = '#c9d1ff') {
    const c = document.createElement('canvas');
    c.width = 256; c.height = 64;
    const g = c.getContext('2d');
    g.clearRect(0, 0, 256, 64);
    g.fillStyle = color;
    g.font = '32px Georgia, serif';
    g.textAlign = 'center'; g.textBaseline = 'middle';
    g.fillText(text, 128, 36);
    const tex = new THREE.CanvasTexture(c);
    tex.minFilter = THREE.LinearFilter;
    const sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, transparent: true, opacity: 0.85, depthTest: false }));
    sp.position.set(cx, cy, 0.1);
    sp.scale.set(sx, sy, 1);
    this.simScene.add(sp);
    return sp;
  }

  initSimScene() {
    this.simScene.clear();
    this.simCamera = new THREE.OrthographicCamera(-1.15, 1.15, 0.95, -0.95, 0.1, 10);
    this.simCamera.position.z = 1;

    // Gas box outline.
    this.simScene.add(new THREE.LineLoop(
      new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(BOX_X0, BOX_Y0, 0), new THREE.Vector3(BOX_X1, BOX_Y0, 0),
        new THREE.Vector3(BOX_X1, BOX_Y1, 0), new THREE.Vector3(BOX_X0, BOX_Y1, 0),
      ]),
      new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.55 })
    ));

    // Pooled instanced gas balls (colour flashes on collision via instanceColor).
    const ballGeom = new THREE.CircleGeometry(BALL_R * BOX_W, 14);
    this.balls = new THREE.InstancedMesh(
      ballGeom, new THREE.MeshBasicMaterial({ transparent: true, opacity: 0.95 }), NMAX);
    this.balls.frustumCulled = false;
    const zero = this._mtx.makeScale(0, 0, 0);
    for (let i = 0; i < NMAX; i++) { this.balls.setMatrixAt(i, zero); this.balls.setColorAt(i, this._col.set(C_BALL)); }
    this.balls.instanceMatrix.needsUpdate = true;
    this.simScene.add(this.balls);

    // Window-timer bar (frame + fill).
    this.simScene.add(new THREE.LineLoop(
      new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(BOX_X0, BAR_Y0, 0), new THREE.Vector3(BOX_X1, BAR_Y0, 0),
        new THREE.Vector3(BOX_X1, BAR_Y1, 0), new THREE.Vector3(BOX_X0, BAR_Y1, 0),
      ]),
      new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.35 })
    ));
    this.timerFill = new THREE.Mesh(new THREE.PlaneGeometry(1, 1),
      new THREE.MeshBasicMaterial({ color: 0x6ee7b7, transparent: true, opacity: 0.6 }));
    this.timerFill.position.z = 0.01;
    this.simScene.add(this.timerFill);

    // Histogram baseline.
    this.simScene.add(new THREE.Line(
      new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(HIST_X0 - HIST_DX * 0.6, HIST_FLOOR, 0),
        new THREE.Vector3(HIST_X0 + (KMAX + 0.6) * HIST_DX, HIST_FLOOR, 0),
      ]),
      new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.34 })
    ));

    // Pooled collisions-per-window bars; k = 0 (empty windows) gold.
    const barGeom = new THREE.PlaneGeometry(1, 1);
    const goldMat = new THREE.MeshBasicMaterial({ color: C_EMPTY, transparent: true, opacity: 0.95 });
    const cyanMat = new THREE.MeshBasicMaterial({ color: C_BAR, transparent: true, opacity: 0.85 });
    this.barMeshes = [];
    for (let k = 0; k <= KMAX; k++) {
      const m = new THREE.Mesh(barGeom, k === 0 ? goldMat : cyanMat);
      m.position.set(HIST_X0 + k * HIST_DX, HIST_FLOOR, 0);
      m.scale.set(HIST_DX * 0.82, 1e-4, 1);
      this.simScene.add(m);
      this.barMeshes.push(m);
    }

    // Poisson(λ̄) envelope, rescaled to the live window total each frame.
    const envPositions = new Float32Array((KMAX + 1) * 3);
    for (let k = 0; k <= KMAX; k++) {
      envPositions[k * 3] = HIST_X0 + k * HIST_DX;
      envPositions[k * 3 + 1] = HIST_FLOOR;
      envPositions[k * 3 + 2] = 0.01;
    }
    this.envGeom = new THREE.BufferGeometry();
    this.envGeom.setAttribute('position', new THREE.BufferAttribute(envPositions, 3));
    this.simScene.add(new THREE.Line(this.envGeom,
      new THREE.LineBasicMaterial({ color: 0x7c83fd, transparent: true, opacity: 0.65 })));

    // Static captions (created once).
    this._label('2D gas: elastic collisions', (BOX_X0 + BOX_X1) / 2, BOX_Y1 + 0.09, 0.52, 0.05);
    this._label('window timer', (BOX_X0 + BOX_X1) / 2, BAR_Y1 - 0.055, 0.3, 0.038, '#9aa0c8');
    this._label('collisions per window →', HIST_X0 + (KMAX / 2) * HIST_DX, HIST_FLOOR - 0.075, 0.44, 0.04);
    this._label('empty', HIST_X0, HIST_FLOOR + BAR_MAX_H + 0.06, 0.16, 0.04, '#f7c948');
    this._label('P(0)=e^(−λ)', HIST_X0 + 0.02, HIST_FLOOR + BAR_MAX_H + 0.02, 0.22, 0.038, '#f7c948');
  }

  updateSimScene() {
    if (!this.balls) return;
    const n = this.n, mtx = this._mtx, bm = this.balls, now = this.boardClock;

    // Gas balls: place, and flash toward gold right after a collision.
    for (let i = 0; i < NMAX; i++) {
      if (i < n) {
        mtx.makeTranslation(this._sx(this.px[i]), this._sy(this.py[i]), 0.02);
        bm.setMatrixAt(i, mtx);
        const age = now - this.flash[i];
        const lit = this.flash[i] >= 0 && age >= 0 && age < FLASH_DUR ? 1 - age / FLASH_DUR : 0;
        bm.setColorAt(i, this._col.set(C_BALL).lerp(this._tmpFlash(), lit));
      } else {
        mtx.makeScale(0, 0, 0);
        bm.setMatrixAt(i, mtx);
      }
    }
    bm.instanceMatrix.needsUpdate = true;
    if (bm.instanceColor) bm.instanceColor.needsUpdate = true;

    // Window timer fill.
    const frac = Math.min(1, this.winClock / this.windowW);
    const w = Math.max(1e-4, BOX_W * frac);
    this.timerFill.scale.set(w, BAR_Y1 - BAR_Y0 - 0.008, 1);
    this.timerFill.position.set(BOX_X0 + w / 2, (BAR_Y0 + BAR_Y1) / 2, 0.01);

    // Histogram of collisions-per-window + Poisson envelope.
    let maxC = 1;
    for (let k = 0; k <= KMAX; k++) if (this.winHist[k] > maxC) maxC = this.winHist[k];
    for (let k = 0; k <= KMAX; k++) {
      const h = Math.max(this.winHist[k] / maxC * BAR_MAX_H, 1e-4);
      const m = this.barMeshes[k];
      m.scale.y = h;
      m.position.y = HIST_FLOOR + h / 2;
    }
    const lam = this._lambda();
    if (lam > 0) {
      let f = 1;
      for (let k = 0; k <= KMAX; k++) {
        if (k > 0) f *= k;
        this.poisProb[k] = Math.exp(-lam) * Math.pow(lam, k) / f;
      }
    }
    const env = this.envGeom.attributes.position.array;
    for (let k = 0; k <= KMAX; k++) {
      const h = (this.winCount > 0 && lam > 0) ? this.winCount * this.poisProb[k] / maxC * BAR_MAX_H : 0;
      env[k * 3 + 1] = HIST_FLOOR + h;
    }
    this.envGeom.attributes.position.needsUpdate = true;
  }

  _tmpFlash() {
    if (!this._flashCol) this._flashCol = new THREE.Color(C_FLASH);
    return this._flashCol;
  }
}

registerSim(CollisionGasE);
