// GENERATED by tools/gen_curator_data.py - do not edit by hand.
window.CURATION_DATA = {
 "generated": true,
 "groups": [
  {
   "label": "Proof webs",
   "items": [
    {
     "id": "compactness",
     "nav": "Compactness",
     "title": "The compactness equivalence web",
     "eyebrow": "Compactness lab",
     "kind": "section"
    },
    {
     "id": "mst",
     "nav": "MST",
     "title": "Minimum spanning tree proof web",
     "eyebrow": "Greedy proof lab",
     "kind": "section"
    },
    {
     "id": "operators",
     "nav": "Fourier",
     "title": "Spatial and frequency operator zoo",
     "eyebrow": "Fourier proof lab",
     "kind": "section"
    },
    {
     "id": "trig-complex",
     "nav": "Trig & Complex",
     "title": "Trigonometry, complex numbers, and hyperbolic functions",
     "eyebrow": "Trig identity lab",
     "kind": "section"
    },
    {
     "id": "fractals",
     "nav": "Fractals",
     "title": "Dimension definitions and examples",
     "eyebrow": "Fractal geometry lab",
     "kind": "section"
    },
    {
     "id": "noise",
     "nav": "Noise",
     "title": "fBM, spectra, and procedural noise",
     "eyebrow": "Noise and roughness lab",
     "kind": "section"
    },
    {
     "id": "spectral",
     "nav": "Spectral",
     "title": "Spectral & eigendecomposition",
     "eyebrow": "Spectral lab",
     "kind": "zoo",
     "stats": "15 nodes · 20 relations"
    },
    {
     "id": "gauss-bonnet",
     "nav": "Curvature",
     "title": "Curvature & Gauss-Bonnet",
     "eyebrow": "Curvature lab",
     "kind": "zoo",
     "stats": "11 nodes · 13 relations"
    },
    {
     "id": "ac-equivalents",
     "nav": "Choice",
     "title": "The Axiom of Choice and its equivalents",
     "eyebrow": "Choice lab",
     "kind": "zoo",
     "stats": "12 nodes · 12 relations"
    },
    {
     "id": "induction",
     "nav": "Induction",
     "title": "Induction principles",
     "eyebrow": "Choice lab",
     "kind": "zoo",
     "stats": "10 nodes · 12 relations"
    },
    {
     "id": "complexity",
     "nav": "Complexity",
     "title": "The complexity class zoo",
     "eyebrow": "Choice lab",
     "kind": "zoo",
     "stats": "14 nodes · 21 relations"
    },
    {
     "id": "galois",
     "nav": "Galois",
     "title": "The Galois Correspondence",
     "eyebrow": "Field theory · Galois theory",
     "kind": "zoo",
     "stats": "12 nodes · 16 relations"
    },
    {
     "id": "duality",
     "nav": "Duality",
     "title": "Optimization Duality",
     "eyebrow": "Min-max theorems and LP duality",
     "kind": "zoo",
     "stats": "10 nodes · 12 relations"
    },
    {
     "id": "completeness",
     "nav": "Completeness",
     "title": "Completeness & Fixed Points",
     "eyebrow": "Metric spaces",
     "kind": "zoo",
     "stats": "12 nodes · 16 relations"
    },
    {
     "id": "category",
     "nav": "Category",
     "title": "Universal Properties, Limits & Adjunctions",
     "eyebrow": "Category Theory",
     "kind": "zoo",
     "stats": "12 nodes · 14 relations"
    },
    {
     "id": "group-theory",
     "nav": "Groups",
     "title": "Group theory core",
     "eyebrow": "Abstract algebra",
     "kind": "zoo",
     "stats": "14 nodes · 16 relations"
    },
    {
     "id": "measure-theory",
     "nav": "Measure",
     "title": "Measure-theory foundations",
     "eyebrow": "Measure theory",
     "kind": "zoo",
     "stats": "12 nodes · 14 relations"
    },
    {
     "id": "hilbert-operators",
     "nav": "Hilbert",
     "title": "Hilbert spaces & bounded operators",
     "eyebrow": "Functional analysis",
     "kind": "zoo",
     "stats": "13 nodes · 13 relations"
    },
    {
     "id": "number-theory",
     "nav": "Numbers",
     "title": "Number theory core",
     "eyebrow": "Elementary & modular number theory",
     "kind": "zoo",
     "stats": "12 nodes · 15 relations"
    },
    {
     "id": "convexity",
     "nav": "Convexity",
     "title": "Convexity & separation",
     "eyebrow": "Convex analysis",
     "kind": "zoo",
     "stats": "12 nodes · 14 relations"
    }
   ]
  },
  {
   "label": "Ladders",
   "items": [
    {
     "id": "convergence",
     "nav": "Convergence",
     "title": "Modes of convergence",
     "eyebrow": "Convergence lab",
     "kind": "zoo",
     "stats": "8 nodes · 15 relations"
    },
    {
     "id": "integrals",
     "nav": "Integrals",
     "title": "Which functions become integrable?",
     "eyebrow": "Integral zoo",
     "kind": "section"
    },
    {
     "id": "field-integrals",
     "nav": "Field integrals",
     "title": "Static domains and moving-domain transport",
     "eyebrow": "Field integral lab",
     "kind": "section"
    },
    {
     "id": "axioms",
     "nav": "Axioms",
     "title": "From T0 to the full separation taxonomy",
     "eyebrow": "Separation ladder",
     "kind": "section"
    }
   ]
  },
  {
   "label": "Catalogs",
   "items": [
    {
     "id": "counterexamples",
     "nav": "Counterexamples",
     "title": "Spaces that separate similar definitions",
     "eyebrow": "Counterexample lab",
     "kind": "section"
    },
    {
     "id": "spaces",
     "nav": "Spaces",
     "title": "Classic spaces at a glance",
     "eyebrow": "Invariant explorer",
     "kind": "section"
    }
   ]
  },
  {
   "label": "Map",
   "items": [
    {
     "id": "bridges",
     "nav": "Bridges",
     "title": "How the zoos connect",
     "eyebrow": "The map",
     "kind": "section"
    },
    {
     "id": "atlas",
     "nav": "Atlas",
     "title": "Search the concept atlas",
     "eyebrow": "Concept atlas",
     "kind": "section"
    },
    {
     "id": "graphics",
     "nav": "Graphics",
     "title": "What topology actually does in geometry processing",
     "eyebrow": "Graphics lens",
     "kind": "section"
    },
    {
     "id": "roadmap",
     "nav": "Roadmap",
     "title": "The chapter-level map — where this started",
     "eyebrow": "Roadmap",
     "kind": "section"
    }
   ]
  },
  {
   "label": "Roadmaps",
   "items": [
    {
     "id": "algorithms",
     "nav": "Algorithms",
     "title": "Techniques as clusters of ideas",
     "eyebrow": "Algorithms roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "arrays-hashing",
       "title": "Arrays & hashing",
       "tier": "foundations",
       "symbol": "{ }"
      },
      {
       "id": "two-pointers",
       "title": "Two pointers",
       "tier": "foundations",
       "symbol": "→←"
      },
      {
       "id": "sliding-window",
       "title": "Sliding window",
       "tier": "foundations",
       "symbol": "[..]→"
      },
      {
       "id": "prefix-sums",
       "title": "Prefix sums & difference arrays",
       "tier": "foundations",
       "symbol": "Σ/Δ"
      },
      {
       "id": "binary-search",
       "title": "Binary search",
       "tier": "foundations",
       "symbol": "bsrch"
      },
      {
       "id": "stack-monotonic",
       "title": "Stacks & monotonic stacks",
       "tier": "foundations",
       "symbol": "[LIFO]"
      },
      {
       "id": "heap-pq",
       "title": "Heaps / priority queues",
       "tier": "structures",
       "symbol": "PQ"
      },
      {
       "id": "intervals",
       "title": "Intervals",
       "tier": "foundations",
       "symbol": "[a,b]"
      },
      {
       "id": "linked-list",
       "title": "Linked lists",
       "tier": "structures",
       "symbol": "→●→●"
      },
      {
       "id": "trees-bst",
       "title": "Trees & BSTs",
       "tier": "structures",
       "symbol": "Tree"
      },
      {
       "id": "tries",
       "title": "Tries",
       "tier": "structures",
       "symbol": "TRIE"
      },
      {
       "id": "range-queries",
       "title": "Range queries: segment tree / Fenwick",
       "tier": "structures",
       "symbol": "SegT"
      },
      {
       "id": "graph-traversal",
       "title": "Graph traversal (BFS/DFS)",
       "tier": "graphs",
       "symbol": "BFS"
      },
      {
       "id": "union-find",
       "title": "Union-Find (DSU)",
       "tier": "graphs",
       "symbol": "DSU"
      },
      {
       "id": "topological-sort",
       "title": "Topological sort",
       "tier": "graphs",
       "symbol": "Topo"
      },
      {
       "id": "shortest-paths",
       "title": "Shortest paths",
       "tier": "graphs",
       "symbol": "δ(u,v)"
      },
      {
       "id": "mst-algorithms",
       "title": "Minimum spanning tree (Kruskal/Prim)",
       "tier": "graphs",
       "symbol": "MST"
      },
      {
       "id": "graph-advanced",
       "title": "Advanced graphs (flows, matching, SCC)",
       "tier": "graphs",
       "symbol": "Flow"
      },
      {
       "id": "greedy",
       "title": "Greedy",
       "tier": "paradigms",
       "symbol": "≼best"
      },
      {
       "id": "divide-and-conquer",
       "title": "Divide & conquer",
       "tier": "paradigms",
       "symbol": "D&C"
      },
      {
       "id": "backtracking",
       "title": "Backtracking",
       "tier": "paradigms",
       "symbol": "↩DFS"
      },
      {
       "id": "dynamic-programming",
       "title": "Dynamic programming",
       "tier": "paradigms",
       "symbol": "DP"
      },
      {
       "id": "bit-manipulation",
       "title": "Bit manipulation",
       "tier": "paradigms",
       "symbol": "b&1"
      },
      {
       "id": "math-number-theory",
       "title": "Math & number theory",
       "tier": "paradigms",
       "symbol": "gcd·p"
      },
      {
       "id": "strings",
       "title": "String matching (KMP / Z / rolling hash)",
       "tier": "paradigms",
       "symbol": "π/Z/h"
      }
     ],
     "stats": "25 topics · 205 sub-topics"
    },
    {
     "id": "hypercomplex",
     "nav": "Hypercomplex",
     "title": "Complex, quaternion & geometric algebra",
     "eyebrow": "Number-systems roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "complex-field",
       "title": "The complex field ℂ",
       "tier": "complex",
       "symbol": "ℂ"
      },
      {
       "id": "complex-plane",
       "title": "The complex plane",
       "tier": "complex",
       "symbol": "a+bi"
      },
      {
       "id": "polar-euler",
       "title": "Polar form & Euler’s formula",
       "tier": "complex",
       "symbol": "polar"
      },
      {
       "id": "roots-of-unity",
       "title": "Roots of unity",
       "tier": "complex",
       "symbol": "roots"
      },
      {
       "id": "complex-maps",
       "title": "Analytic & conformal maps",
       "tier": "complex",
       "symbol": "f(z)"
      },
      {
       "id": "quaternion-algebra",
       "title": "The quaternion algebra ℍ",
       "tier": "quaternion",
       "symbol": "ℍ"
      },
      {
       "id": "quaternion-norm",
       "title": "Norm, conjugate, inverse",
       "tier": "quaternion",
       "symbol": "|q|"
      },
      {
       "id": "quaternion-rotation",
       "title": "Rotations with quaternions",
       "tier": "quaternion",
       "symbol": "qvq*"
      },
      {
       "id": "quaternion-interp",
       "title": "Interpolation & comparison",
       "tier": "quaternion",
       "symbol": "slerp"
      },
      {
       "id": "dual-quaternions",
       "title": "Dual quaternions",
       "tier": "quaternion",
       "symbol": "dualq"
      },
      {
       "id": "cayley-dickson",
       "title": "The Cayley–Dickson construction",
       "tier": "ladder",
       "symbol": "CayD"
      },
      {
       "id": "octonions",
       "title": "Octonions 𝕆",
       "tier": "ladder",
       "symbol": "𝕆"
      },
      {
       "id": "division-algebras",
       "title": "Normed division algebras",
       "tier": "ladder",
       "symbol": "1248"
      },
      {
       "id": "geometric-product",
       "title": "The geometric product",
       "tier": "geometric",
       "symbol": "ab"
      },
      {
       "id": "grades-blades",
       "title": "Grades, blades & multivectors",
       "tier": "geometric",
       "symbol": "a∧b"
      },
      {
       "id": "duality-pseudoscalar",
       "title": "Pseudoscalar & duality",
       "tier": "geometric",
       "symbol": "I"
      },
      {
       "id": "rotors-reflections",
       "title": "Rotors & reflections",
       "tier": "geometric",
       "symbol": "rotor"
      },
      {
       "id": "ga-embeds",
       "title": "GA recovers ℂ and ℍ",
       "tier": "geometric",
       "symbol": "Cl+"
      },
      {
       "id": "spinors",
       "title": "Spinors & physics algebras",
       "tier": "geometric",
       "symbol": "spin"
      },
      {
       "id": "conformal-ga",
       "title": "Conformal geometric algebra",
       "tier": "geometric",
       "symbol": "CGA"
      },
      {
       "id": "projective-ga",
       "title": "Projective geometric algebra",
       "tier": "geometric",
       "symbol": "PGA"
      },
      {
       "id": "rotations-unified",
       "title": "One idea: rotation everywhere",
       "tier": "unifying",
       "symbol": "rot"
      },
      {
       "id": "exponential-map",
       "title": "The exponential map",
       "tier": "unifying",
       "symbol": "exp"
      },
      {
       "id": "lie-spin-groups",
       "title": "Lie & spin groups",
       "tier": "unifying",
       "symbol": "Spin"
      }
     ],
     "stats": "24 topics · 165 sub-topics"
    },
    {
     "id": "groups-roadmap",
     "nav": "Group theory",
     "title": "From the axioms to symmetry groups",
     "eyebrow": "Group theory roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "gt-axioms",
       "title": "Groups & axioms",
       "tier": "foundations",
       "symbol": "G"
      },
      {
       "id": "gt-examples",
       "title": "Key examples",
       "tier": "foundations",
       "symbol": "Sn"
      },
      {
       "id": "gt-subgroups",
       "title": "Subgroups & Lagrange",
       "tier": "foundations",
       "symbol": "H<G"
      },
      {
       "id": "gt-cyclic",
       "title": "Cyclic groups",
       "tier": "foundations",
       "symbol": "Zn"
      },
      {
       "id": "gt-homomorphisms",
       "title": "Homomorphisms",
       "tier": "foundations",
       "symbol": "hom"
      },
      {
       "id": "gt-generators",
       "title": "Generators & presentations",
       "tier": "foundations",
       "symbol": "<S>"
      },
      {
       "id": "gt-normal",
       "title": "Normal subgroups & quotients",
       "tier": "structure",
       "symbol": "G/N"
      },
      {
       "id": "gt-iso-theorems",
       "title": "Isomorphism theorems",
       "tier": "structure",
       "symbol": "iso"
      },
      {
       "id": "gt-actions",
       "title": "Group actions",
       "tier": "structure",
       "symbol": "G·X"
      },
      {
       "id": "gt-conjugacy",
       "title": "Conjugacy & class equation",
       "tier": "structure",
       "symbol": "conj"
      },
      {
       "id": "gt-products",
       "title": "Direct & semidirect products",
       "tier": "structure",
       "symbol": "prod"
      },
      {
       "id": "gt-abelian",
       "title": "Finite abelian structure",
       "tier": "structure",
       "symbol": "abel"
      },
      {
       "id": "gt-sylow",
       "title": "Sylow theorems",
       "tier": "classification",
       "symbol": "Sylp"
      },
      {
       "id": "gt-pgroups",
       "title": "p-groups & nilpotent",
       "tier": "classification",
       "symbol": "p^n"
      },
      {
       "id": "gt-solvable",
       "title": "Solvable groups",
       "tier": "classification",
       "symbol": "solv"
      },
      {
       "id": "gt-composition",
       "title": "Composition series & Jordan–Hölder",
       "tier": "classification",
       "symbol": "J-H"
      },
      {
       "id": "gt-simple",
       "title": "Simple groups",
       "tier": "classification",
       "symbol": "An"
      },
      {
       "id": "gt-classify-small",
       "title": "Classifying small groups",
       "tier": "classification",
       "symbol": "|G|"
      },
      {
       "id": "gt-representations",
       "title": "Linear representations",
       "tier": "representation",
       "symbol": "rep"
      },
      {
       "id": "gt-maschke-schur",
       "title": "Maschke & Schur",
       "tier": "representation",
       "symbol": "Schur"
      },
      {
       "id": "gt-characters",
       "title": "Characters & orthogonality",
       "tier": "representation",
       "symbol": "χ"
      },
      {
       "id": "gt-character-tables",
       "title": "Character tables",
       "tier": "representation",
       "symbol": "table"
      },
      {
       "id": "gt-lie",
       "title": "Lie groups & algebras",
       "tier": "frontiers",
       "symbol": "Lie"
      },
      {
       "id": "gt-symmetry-apps",
       "title": "Symmetry & counting",
       "tier": "frontiers",
       "symbol": "sym"
      }
     ],
     "stats": "24 topics · 159 sub-topics"
    },
    {
     "id": "topology-roadmap",
     "nav": "Algebraic topology",
     "title": "Turning spaces into algebra",
     "eyebrow": "Algebraic topology roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "at-spaces",
       "title": "Spaces & invariants",
       "tier": "foundations",
       "symbol": "top"
      },
      {
       "id": "at-homotopy",
       "title": "Homotopy equivalence",
       "tier": "foundations",
       "symbol": "htpy"
      },
      {
       "id": "at-retracts",
       "title": "Retracts",
       "tier": "foundations",
       "symbol": "retr"
      },
      {
       "id": "at-cw",
       "title": "CW complexes",
       "tier": "foundations",
       "symbol": "CW"
      },
      {
       "id": "at-pi1",
       "title": "The fundamental group",
       "tier": "fundamental",
       "symbol": "pi1"
      },
      {
       "id": "at-van-kampen",
       "title": "Van Kampen",
       "tier": "fundamental",
       "symbol": "vK"
      },
      {
       "id": "at-covering",
       "title": "Covering spaces",
       "tier": "fundamental",
       "symbol": "cov"
      },
      {
       "id": "at-deck",
       "title": "Deck transformations",
       "tier": "fundamental",
       "symbol": "deck"
      },
      {
       "id": "at-higher-homotopy",
       "title": "Higher homotopy groups",
       "tier": "fundamental",
       "symbol": "pin"
      },
      {
       "id": "at-simplicial",
       "title": "Simplicial homology",
       "tier": "homology",
       "symbol": "simp"
      },
      {
       "id": "at-singular",
       "title": "Singular homology",
       "tier": "homology",
       "symbol": "Hn"
      },
      {
       "id": "at-euler-char",
       "title": "Euler characteristic",
       "tier": "homology",
       "symbol": "χ"
      },
      {
       "id": "at-mayer-vietoris",
       "title": "Mayer–Vietoris",
       "tier": "homology",
       "symbol": "MV"
      },
      {
       "id": "at-homology-comp",
       "title": "Homology of spheres & surfaces",
       "tier": "homology",
       "symbol": "H(S)"
      },
      {
       "id": "at-degree",
       "title": "Degree & applications",
       "tier": "homology",
       "symbol": "deg"
      },
      {
       "id": "at-cohomology",
       "title": "Singular cohomology",
       "tier": "cohomology",
       "symbol": "H^n"
      },
      {
       "id": "at-cup-product",
       "title": "Cup product",
       "tier": "cohomology",
       "symbol": "cup"
      },
      {
       "id": "at-de-rham",
       "title": "de Rham cohomology",
       "tier": "cohomology",
       "symbol": "dR"
      },
      {
       "id": "at-poincare",
       "title": "Poincaré duality",
       "tier": "cohomology",
       "symbol": "PD"
      },
      {
       "id": "at-universal-coeff",
       "title": "Universal coefficients & Künneth",
       "tier": "cohomology",
       "symbol": "UCT"
      },
      {
       "id": "at-fiber-bundles",
       "title": "Fiber bundles & fibrations",
       "tier": "advanced",
       "symbol": "fib"
      },
      {
       "id": "at-char-classes",
       "title": "Characteristic classes",
       "tier": "advanced",
       "symbol": "w,c"
      },
      {
       "id": "at-fixed-points",
       "title": "Fixed-point theorems",
       "tier": "advanced",
       "symbol": "fix"
      },
      {
       "id": "at-tda",
       "title": "Persistent homology (TDA)",
       "tier": "advanced",
       "symbol": "TDA"
      }
     ],
     "stats": "24 topics · 165 sub-topics"
    },
    {
     "id": "complex-analysis-roadmap",
     "nav": "Complex analysis",
     "title": "Holomorphy, residues & Riemann surfaces",
     "eyebrow": "Complex analysis roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "ca-holomorphy",
       "title": "Holomorphic functions & Cauchy–Riemann",
       "tier": "foundations",
       "symbol": "CR"
      },
      {
       "id": "ca-power-series",
       "title": "Power series & analyticity",
       "tier": "foundations",
       "symbol": "Σaz"
      },
      {
       "id": "ca-elementary",
       "title": "Elementary functions & branches",
       "tier": "foundations",
       "symbol": "e^z"
      },
      {
       "id": "ca-conformal-intro",
       "title": "Conformality",
       "tier": "foundations",
       "symbol": "conf"
      },
      {
       "id": "ca-contour",
       "title": "Contour integration",
       "tier": "integration",
       "symbol": "∮"
      },
      {
       "id": "ca-cauchy-theorem",
       "title": "Cauchy theorem",
       "tier": "integration",
       "symbol": "∮=0"
      },
      {
       "id": "ca-cauchy-formula",
       "title": "Cauchy integral formula",
       "tier": "integration",
       "symbol": "CIF"
      },
      {
       "id": "ca-max-modulus",
       "title": "Maximum modulus & Schwarz",
       "tier": "integration",
       "symbol": "max"
      },
      {
       "id": "ca-laurent",
       "title": "Laurent series & singularities",
       "tier": "series",
       "symbol": "Laur"
      },
      {
       "id": "ca-residues",
       "title": "The residue theorem",
       "tier": "series",
       "symbol": "Res"
      },
      {
       "id": "ca-argument-principle",
       "title": "Argument principle & Rouché",
       "tier": "series",
       "symbol": "arg"
      },
      {
       "id": "ca-meromorphic",
       "title": "Meromorphic & entire functions",
       "tier": "series",
       "symbol": "mero"
      },
      {
       "id": "ca-mobius",
       "title": "Möbius transformations",
       "tier": "geometry",
       "symbol": "Möb"
      },
      {
       "id": "ca-riemann-mapping",
       "title": "The Riemann mapping theorem",
       "tier": "geometry",
       "symbol": "RMT"
      },
      {
       "id": "ca-analytic-continuation",
       "title": "Analytic continuation & monodromy",
       "tier": "geometry",
       "symbol": "cont"
      },
      {
       "id": "ca-riemann-surfaces",
       "title": "Riemann surfaces",
       "tier": "geometry",
       "symbol": "surf"
      },
      {
       "id": "ca-special-functions",
       "title": "The Gamma & zeta functions",
       "tier": "advanced",
       "symbol": "Γ,ζ"
      },
      {
       "id": "ca-harmonic",
       "title": "Harmonic functions & potential theory",
       "tier": "advanced",
       "symbol": "harm"
      },
      {
       "id": "ca-elliptic",
       "title": "Elliptic & modular functions",
       "tier": "advanced",
       "symbol": "℘"
      },
      {
       "id": "ca-several-variables",
       "title": "Several complex variables",
       "tier": "advanced",
       "symbol": "Cⁿ"
      }
     ],
     "stats": "20 topics · 141 sub-topics"
    },
    {
     "id": "geometry-roadmap",
     "nav": "Geometry",
     "title": "Manifolds, curvature & Gauss–Bonnet",
     "eyebrow": "Differential geometry roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "dg-manifolds",
       "title": "Smooth manifolds",
       "tier": "manifolds",
       "symbol": "M"
      },
      {
       "id": "dg-tangent",
       "title": "Tangent & cotangent spaces",
       "tier": "manifolds",
       "symbol": "TM"
      },
      {
       "id": "dg-vector-fields",
       "title": "Vector fields & flows",
       "tier": "manifolds",
       "symbol": "[X,Y]"
      },
      {
       "id": "dg-submanifolds",
       "title": "Immersions, embeddings & Sard",
       "tier": "manifolds",
       "symbol": "Sard"
      },
      {
       "id": "dg-forms",
       "title": "Differential forms",
       "tier": "calculus",
       "symbol": "ω"
      },
      {
       "id": "dg-stokes",
       "title": "Integration & Stokes",
       "tier": "calculus",
       "symbol": "∫dω"
      },
      {
       "id": "dg-de-rham",
       "title": "de Rham cohomology",
       "tier": "calculus",
       "symbol": "dR"
      },
      {
       "id": "dg-lie-derivative",
       "title": "Lie derivative & Cartan calculus",
       "tier": "calculus",
       "symbol": "L_X"
      },
      {
       "id": "dg-bundles",
       "title": "Fiber & vector bundles",
       "tier": "bundles",
       "symbol": "E→M"
      },
      {
       "id": "dg-connections",
       "title": "Connections & covariant derivative",
       "tier": "bundles",
       "symbol": "∇"
      },
      {
       "id": "dg-curvature-tensor",
       "title": "Curvature of a connection",
       "tier": "bundles",
       "symbol": "curv"
      },
      {
       "id": "dg-principal",
       "title": "Principal bundles & gauge",
       "tier": "bundles",
       "symbol": "gauge"
      },
      {
       "id": "dg-metric",
       "title": "Riemannian metrics",
       "tier": "riemannian",
       "symbol": "g"
      },
      {
       "id": "dg-levi-civita",
       "title": "The Levi-Civita connection",
       "tier": "riemannian",
       "symbol": "LC"
      },
      {
       "id": "dg-geodesics",
       "title": "Geodesics & the exponential map",
       "tier": "riemannian",
       "symbol": "geo"
      },
      {
       "id": "dg-curvature-riem",
       "title": "Riemann, Ricci & sectional curvature",
       "tier": "riemannian",
       "symbol": "Ricci"
      },
      {
       "id": "dg-gauss-bonnet",
       "title": "Gauss–Bonnet in all dimensions",
       "tier": "global",
       "symbol": "2πχ"
      },
      {
       "id": "dg-comparison",
       "title": "Comparison & global theorems",
       "tier": "global",
       "symbol": "comp"
      },
      {
       "id": "dg-hodge",
       "title": "Hodge theory",
       "tier": "global",
       "symbol": "Hodge"
      },
      {
       "id": "dg-relativity",
       "title": "Lorentzian geometry & GR",
       "tier": "global",
       "symbol": "GR"
      }
     ],
     "stats": "20 topics · 137 sub-topics"
    },
    {
     "id": "functional-analysis-roadmap",
     "nav": "Functional analysis",
     "title": "Banach, Hilbert & the spectral theorem",
     "eyebrow": "Functional analysis roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "fa-normed",
       "title": "Normed & Banach spaces",
       "tier": "spaces",
       "symbol": "Bnch"
      },
      {
       "id": "fa-lp",
       "title": "Lp & sequence spaces",
       "tier": "spaces",
       "symbol": "Lᵖ"
      },
      {
       "id": "fa-bounded-operators",
       "title": "Bounded linear operators",
       "tier": "spaces",
       "symbol": "B(X)"
      },
      {
       "id": "fa-hahn-banach",
       "title": "Dual spaces & Hahn–Banach",
       "tier": "theorems",
       "symbol": "H–B"
      },
      {
       "id": "fa-baire",
       "title": "Baire category & the three principles",
       "tier": "theorems",
       "symbol": "Baire"
      },
      {
       "id": "fa-weak-topologies",
       "title": "Weak & weak* topologies",
       "tier": "theorems",
       "symbol": "weak*"
      },
      {
       "id": "fa-compact-operators",
       "title": "Compact operators",
       "tier": "theorems",
       "symbol": "cmpt"
      },
      {
       "id": "fa-hilbert",
       "title": "Hilbert spaces",
       "tier": "hilbert",
       "symbol": "H"
      },
      {
       "id": "fa-riesz",
       "title": "Riesz representation & projections",
       "tier": "hilbert",
       "symbol": "Riesz"
      },
      {
       "id": "fa-fourier-hilbert",
       "title": "Fourier as a unitary",
       "tier": "hilbert",
       "symbol": "L²F"
      },
      {
       "id": "fa-spectrum",
       "title": "Spectrum & resolvent",
       "tier": "operators",
       "symbol": "σ(T)"
      },
      {
       "id": "fa-self-adjoint",
       "title": "Self-adjoint & normal operators",
       "tier": "operators",
       "symbol": "T=T*"
      },
      {
       "id": "fa-unbounded",
       "title": "Unbounded operators",
       "tier": "operators",
       "symbol": "unbd"
      },
      {
       "id": "fa-c-star",
       "title": "Banach & C*-algebras",
       "tier": "operators",
       "symbol": "C*"
      },
      {
       "id": "fa-spectral-measure",
       "title": "Spectral measures & functional calculus",
       "tier": "spectral",
       "symbol": "PVM"
      },
      {
       "id": "fa-semigroups",
       "title": "Operator semigroups",
       "tier": "spectral",
       "symbol": "e^{tA}"
      },
      {
       "id": "fa-distributions",
       "title": "Distributions",
       "tier": "spectral",
       "symbol": "D′"
      },
      {
       "id": "fa-sobolev",
       "title": "Sobolev spaces",
       "tier": "spectral",
       "symbol": "Hˢ"
      }
     ],
     "stats": "18 topics · 125 sub-topics"
    },
    {
     "id": "probability-roadmap",
     "nav": "Probability",
     "title": "Measure, martingales & Itô calculus",
     "eyebrow": "Probability roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "pr-measure",
       "title": "Probability spaces & measure",
       "tier": "foundations",
       "symbol": "P"
      },
      {
       "id": "pr-random-variables",
       "title": "Random variables & distributions",
       "tier": "foundations",
       "symbol": "r.v."
      },
      {
       "id": "pr-expectation",
       "title": "Expectation & inequalities",
       "tier": "foundations",
       "symbol": "E[X]"
      },
      {
       "id": "pr-independence",
       "title": "Independence & Borel–Cantelli",
       "tier": "foundations",
       "symbol": "indep"
      },
      {
       "id": "pr-lln",
       "title": "Laws of large numbers",
       "tier": "limits",
       "symbol": "LLN"
      },
      {
       "id": "pr-clt",
       "title": "The central limit theorem",
       "tier": "limits",
       "symbol": "CLT"
      },
      {
       "id": "pr-convergence",
       "title": "Modes of convergence",
       "tier": "limits",
       "symbol": "conv"
      },
      {
       "id": "pr-char-functions",
       "title": "Characteristic & generating functions",
       "tier": "limits",
       "symbol": "φ(t)"
      },
      {
       "id": "pr-conditional",
       "title": "Conditional expectation",
       "tier": "martingales",
       "symbol": "cond"
      },
      {
       "id": "pr-martingales",
       "title": "Martingales & stopping times",
       "tier": "martingales",
       "symbol": "mart"
      },
      {
       "id": "pr-martingale-convergence",
       "title": "Martingale convergence",
       "tier": "martingales",
       "symbol": "Doob"
      },
      {
       "id": "pr-markov",
       "title": "Markov chains",
       "tier": "processes",
       "symbol": "MC"
      },
      {
       "id": "pr-poisson",
       "title": "Poisson & point processes",
       "tier": "processes",
       "symbol": "Pois"
      },
      {
       "id": "pr-brownian",
       "title": "Brownian motion",
       "tier": "processes",
       "symbol": "Bₜ"
      },
      {
       "id": "pr-gaussian",
       "title": "Gaussian processes",
       "tier": "processes",
       "symbol": "Gauss"
      },
      {
       "id": "pr-ito-integral",
       "title": "The Itô integral",
       "tier": "stochastic",
       "symbol": "∫dB"
      },
      {
       "id": "pr-ito-formula",
       "title": "Itô formula",
       "tier": "stochastic",
       "symbol": "Itô"
      },
      {
       "id": "pr-sde",
       "title": "Stochastic differential equations",
       "tier": "stochastic",
       "symbol": "SDE"
      },
      {
       "id": "pr-large-deviations",
       "title": "Large deviations & concentration",
       "tier": "stochastic",
       "symbol": "LDP"
      }
     ],
     "stats": "19 topics · 129 sub-topics"
    },
    {
     "id": "lie-groups-roadmap",
     "nav": "Lie groups",
     "title": "Continuous symmetry: groups, algebras & representations",
     "eyebrow": "Lie groups roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "lie-groups-def",
       "title": "Lie groups: definition & examples",
       "tier": "foundations",
       "symbol": "G"
      },
      {
       "id": "lie-matrix-groups",
       "title": "Matrix Lie groups",
       "tier": "foundations",
       "symbol": "GLn"
      },
      {
       "id": "lie-algebra-of-group",
       "title": "The Lie algebra of a Lie group",
       "tier": "foundations",
       "symbol": "Lie G"
      },
      {
       "id": "lie-exponential",
       "title": "The exponential map",
       "tier": "foundations",
       "symbol": "exp"
      },
      {
       "id": "lie-bch",
       "title": "Baker–Campbell–Hausdorff",
       "tier": "foundations",
       "symbol": "BCH"
      },
      {
       "id": "lie-algebras-def",
       "title": "Lie algebras: axioms",
       "tier": "algebras",
       "symbol": "[,]"
      },
      {
       "id": "lie-subalgebras-ideals",
       "title": "Subalgebras, ideals & homomorphisms",
       "tier": "algebras",
       "symbol": "ideal"
      },
      {
       "id": "lie-solvable-nilpotent",
       "title": "Solvable & nilpotent Lie algebras",
       "tier": "algebras",
       "symbol": "solv"
      },
      {
       "id": "lie-semisimple",
       "title": "Semisimple algebras & the Killing form",
       "tier": "algebras",
       "symbol": "Kill"
      },
      {
       "id": "lie-representations-intro",
       "title": "Representations & the adjoint",
       "tier": "algebras",
       "symbol": "ad"
      },
      {
       "id": "lie-cartan-subalgebra",
       "title": "Cartan subalgebras & roots",
       "tier": "structure",
       "symbol": "CSA"
      },
      {
       "id": "lie-root-systems",
       "title": "Root systems",
       "tier": "structure",
       "symbol": "roots"
      },
      {
       "id": "lie-dynkin",
       "title": "Dynkin diagrams & classification",
       "tier": "structure",
       "symbol": "Dynkin"
      },
      {
       "id": "lie-weyl-group",
       "title": "The Weyl group & chambers",
       "tier": "structure",
       "symbol": "W"
      },
      {
       "id": "lie-highest-weight",
       "title": "Highest weight theory",
       "tier": "representation",
       "symbol": "h.w."
      },
      {
       "id": "lie-weyl-character",
       "title": "Weyl character & dimension formulas",
       "tier": "representation",
       "symbol": "char"
      },
      {
       "id": "lie-peter-weyl",
       "title": "Compact groups & Peter–Weyl",
       "tier": "representation",
       "symbol": "PW"
      },
      {
       "id": "lie-su2-su3",
       "title": "SU(2), SU(3) & physics",
       "tier": "representation",
       "symbol": "SUn"
      },
      {
       "id": "lie-homogeneous",
       "title": "Homogeneous & symmetric spaces",
       "tier": "geometry",
       "symbol": "G/H"
      },
      {
       "id": "lie-gauge-physics",
       "title": "Lie groups in physics & gauge theory",
       "tier": "geometry",
       "symbol": "gauge"
      }
     ],
     "stats": "20 topics · 138 sub-topics"
    },
    {
     "id": "pde-roadmap",
     "nav": "PDEs",
     "title": "Characteristics, the classical trio & weak solutions",
     "eyebrow": "PDE roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "pde-basics",
       "title": "What a PDE is",
       "tier": "foundations",
       "symbol": "PDE"
      },
      {
       "id": "pde-first-order",
       "title": "First-order PDE & characteristics",
       "tier": "foundations",
       "symbol": "char"
      },
      {
       "id": "pde-classification",
       "title": "Classification of second-order equations",
       "tier": "foundations",
       "symbol": "type"
      },
      {
       "id": "pde-boundary-conditions",
       "title": "Boundary & initial conditions",
       "tier": "foundations",
       "symbol": "BC"
      },
      {
       "id": "pde-laplace",
       "title": "Laplace & Poisson equations",
       "tier": "classical",
       "symbol": "Δu=0"
      },
      {
       "id": "pde-heat",
       "title": "The heat equation",
       "tier": "classical",
       "symbol": "u_t"
      },
      {
       "id": "pde-wave",
       "title": "The wave equation",
       "tier": "classical",
       "symbol": "u_tt"
      },
      {
       "id": "pde-separation",
       "title": "Separation of variables & Sturm–Liouville",
       "tier": "methods",
       "symbol": "sep"
      },
      {
       "id": "pde-fourier-methods",
       "title": "Transform methods",
       "tier": "methods",
       "symbol": "F[u]"
      },
      {
       "id": "pde-greens",
       "title": "Green's functions & Duhamel",
       "tier": "methods",
       "symbol": "G(x,y)"
      },
      {
       "id": "pde-maximum-principles",
       "title": "Maximum principles",
       "tier": "methods",
       "symbol": "max"
      },
      {
       "id": "pde-energy-methods",
       "title": "Energy methods & a priori estimates",
       "tier": "methods",
       "symbol": "E(t)"
      },
      {
       "id": "pde-sobolev-weak",
       "title": "Weak derivatives & Sobolev spaces",
       "tier": "modern",
       "symbol": "W^k,p"
      },
      {
       "id": "pde-lax-milgram",
       "title": "Variational formulation & Lax–Milgram",
       "tier": "modern",
       "symbol": "LaxM"
      },
      {
       "id": "pde-elliptic-regularity",
       "title": "Elliptic regularity",
       "tier": "modern",
       "symbol": "reg"
      },
      {
       "id": "pde-spectral-eigen",
       "title": "Eigenvalues of the Laplacian",
       "tier": "modern",
       "symbol": "λ_n"
      },
      {
       "id": "pde-nonlinear",
       "title": "Nonlinear PDE",
       "tier": "applied",
       "symbol": "NL"
      },
      {
       "id": "pde-conservation-laws",
       "title": "Conservation laws & shocks",
       "tier": "applied",
       "symbol": "shock"
      },
      {
       "id": "pde-fluids",
       "title": "Euler & Navier–Stokes",
       "tier": "applied",
       "symbol": "NS"
      },
      {
       "id": "pde-numerics",
       "title": "Numerical PDE",
       "tier": "applied",
       "symbol": "FEM"
      }
     ],
     "stats": "20 topics · 159 sub-topics"
    },
    {
     "id": "fourier-roadmap",
     "nav": "Fourier analysis",
     "title": "Frequency: series, transforms & singular integrals",
     "eyebrow": "Fourier analysis roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "fh-fourier-series",
       "title": "Fourier series",
       "tier": "series",
       "symbol": "a_n"
      },
      {
       "id": "fh-convergence",
       "title": "Convergence of Fourier series",
       "tier": "series",
       "symbol": "conv"
      },
      {
       "id": "fh-parseval",
       "title": "Bessel, Parseval & completeness",
       "tier": "series",
       "symbol": "Pars"
      },
      {
       "id": "fh-fourier-transform",
       "title": "The Fourier transform on Rⁿ",
       "tier": "transform",
       "symbol": "FT"
      },
      {
       "id": "fh-convolution",
       "title": "Convolution & approximate identities",
       "tier": "transform",
       "symbol": "f*g"
      },
      {
       "id": "fh-uncertainty",
       "title": "The uncertainty principle",
       "tier": "transform",
       "symbol": "unc"
      },
      {
       "id": "fh-poisson-summation",
       "title": "Poisson summation & sampling",
       "tier": "transform",
       "symbol": "Poiss"
      },
      {
       "id": "fh-tempered-distributions",
       "title": "Schwartz space & tempered distributions",
       "tier": "distributions",
       "symbol": "S′"
      },
      {
       "id": "fh-fourier-pde",
       "title": "Fourier multipliers & PDE",
       "tier": "distributions",
       "symbol": "mult"
      },
      {
       "id": "fh-hardy-littlewood",
       "title": "The maximal function",
       "tier": "lp",
       "symbol": "Mf"
      },
      {
       "id": "fh-interpolation",
       "title": "Interpolation of operators",
       "tier": "lp",
       "symbol": "interp"
      },
      {
       "id": "fh-singular-integrals",
       "title": "Singular integrals",
       "tier": "lp",
       "symbol": "CZ"
      },
      {
       "id": "fh-littlewood-paley",
       "title": "Littlewood–Paley theory",
       "tier": "lp",
       "symbol": "LP"
      },
      {
       "id": "fh-hardy-bmo",
       "title": "Hardy spaces & BMO",
       "tier": "lp",
       "symbol": "BMO"
      },
      {
       "id": "fh-wavelets",
       "title": "Wavelets",
       "tier": "modern",
       "symbol": "ψ"
      },
      {
       "id": "fh-dft-fft",
       "title": "DFT & the FFT",
       "tier": "modern",
       "symbol": "FFT"
      },
      {
       "id": "fh-abstract",
       "title": "Harmonic analysis on groups",
       "tier": "modern",
       "symbol": "Ĝ"
      },
      {
       "id": "fh-oscillatory",
       "title": "Oscillatory & restriction problems",
       "tier": "modern",
       "symbol": "osc"
      }
     ],
     "stats": "18 topics · 142 sub-topics"
    },
    {
     "id": "dynamics-roadmap",
     "nav": "Dynamical systems",
     "title": "Flows, stability, bifurcation & chaos",
     "eyebrow": "Dynamical systems roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "dyn-odes-basics",
       "title": "ODEs & the geometric picture",
       "tier": "existence",
       "symbol": "ODE"
      },
      {
       "id": "dyn-existence",
       "title": "Existence, uniqueness & dependence",
       "tier": "existence",
       "symbol": "Picard"
      },
      {
       "id": "dyn-explicit-methods",
       "title": "Explicitly solvable classes",
       "tier": "existence",
       "symbol": "solve"
      },
      {
       "id": "dyn-linear-systems",
       "title": "Linear systems & the matrix exponential",
       "tier": "linear",
       "symbol": "e^tA"
      },
      {
       "id": "dyn-eigen-phase",
       "title": "Eigenvalues & phase portraits",
       "tier": "linear",
       "symbol": "phase"
      },
      {
       "id": "dyn-nonautonomous",
       "title": "Periodic coefficients & Floquet theory",
       "tier": "linear",
       "symbol": "Floq"
      },
      {
       "id": "dyn-flows",
       "title": "Flows, orbits & invariant sets",
       "tier": "stability",
       "symbol": "flow"
      },
      {
       "id": "dyn-stability",
       "title": "Lyapunov stability",
       "tier": "stability",
       "symbol": "Lyap"
      },
      {
       "id": "dyn-linearization",
       "title": "Linearization & invariant manifolds",
       "tier": "stability",
       "symbol": "HG"
      },
      {
       "id": "dyn-poincare-bendixson",
       "title": "Planar dynamics & limit cycles",
       "tier": "bifurcation",
       "symbol": "PB"
      },
      {
       "id": "dyn-hamiltonian",
       "title": "Hamiltonian & conservative systems",
       "tier": "bifurcation",
       "symbol": "H(p,q)"
      },
      {
       "id": "dyn-bifurcation",
       "title": "Bifurcations & normal forms",
       "tier": "bifurcation",
       "symbol": "bifur"
      },
      {
       "id": "dyn-perturbation",
       "title": "Perturbation & asymptotic methods",
       "tier": "bifurcation",
       "symbol": "pert"
      },
      {
       "id": "dyn-chaos",
       "title": "Chaos & sensitive dependence",
       "tier": "chaos",
       "symbol": "chaos"
      },
      {
       "id": "dyn-maps",
       "title": "Discrete dynamics & period doubling",
       "tier": "chaos",
       "symbol": "logis"
      },
      {
       "id": "dyn-fractal-attractors",
       "title": "Strange attractors & dimension",
       "tier": "chaos",
       "symbol": "attr"
      },
      {
       "id": "dyn-ergodic",
       "title": "Ergodic theory",
       "tier": "chaos",
       "symbol": "ergod"
      },
      {
       "id": "dyn-entropy",
       "title": "Entropy & symbolic dynamics",
       "tier": "chaos",
       "symbol": "h(T)"
      },
      {
       "id": "dyn-numerics-ode",
       "title": "Numerical integration of ODEs",
       "tier": "chaos",
       "symbol": "RK4"
      }
     ],
     "stats": "19 topics · 151 sub-topics"
    },
    {
     "id": "category-roadmap",
     "nav": "Category theory",
     "title": "Functors, adjunctions & derived functors",
     "eyebrow": "Category theory roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "cat-categories",
       "title": "Categories",
       "tier": "categories",
       "symbol": "C"
      },
      {
       "id": "cat-functors",
       "title": "Functors",
       "tier": "categories",
       "symbol": "F"
      },
      {
       "id": "cat-natural",
       "title": "Natural transformations & equivalence",
       "tier": "categories",
       "symbol": "η"
      },
      {
       "id": "cat-yoneda",
       "title": "The Yoneda lemma",
       "tier": "categories",
       "symbol": "Yon"
      },
      {
       "id": "cat-limits",
       "title": "Limits & colimits",
       "tier": "universal",
       "symbol": "lim"
      },
      {
       "id": "cat-universal",
       "title": "Universal properties & free objects",
       "tier": "universal",
       "symbol": "univ"
      },
      {
       "id": "cat-monoidal",
       "title": "Monoidal & enriched categories",
       "tier": "universal",
       "symbol": "⊗"
      },
      {
       "id": "cat-adjunctions",
       "title": "Adjoint functors",
       "tier": "adjoint",
       "symbol": "F⊣G"
      },
      {
       "id": "cat-monads",
       "title": "Monads & algebras",
       "tier": "adjoint",
       "symbol": "T"
      },
      {
       "id": "cat-abelian",
       "title": "Additive & abelian categories",
       "tier": "abelian",
       "symbol": "Ab"
      },
      {
       "id": "cat-chain-complexes",
       "title": "Chain complexes & homology",
       "tier": "abelian",
       "symbol": "d²=0"
      },
      {
       "id": "cat-exact-sequences",
       "title": "Exact sequences & diagram lemmas",
       "tier": "abelian",
       "symbol": "exact"
      },
      {
       "id": "cat-projective-injective",
       "title": "Projectives, injectives & resolutions",
       "tier": "abelian",
       "symbol": "P,I"
      },
      {
       "id": "cat-derived-functors",
       "title": "Derived functors: Ext & Tor",
       "tier": "derived",
       "symbol": "Ext"
      },
      {
       "id": "cat-spectral-sequences",
       "title": "Spectral sequences",
       "tier": "derived",
       "symbol": "E_r"
      },
      {
       "id": "cat-derived-categories",
       "title": "Triangulated & derived categories",
       "tier": "derived",
       "symbol": "D(A)"
      },
      {
       "id": "cat-sheaves",
       "title": "Sheaves & sheaf cohomology",
       "tier": "derived",
       "symbol": "shf"
      },
      {
       "id": "cat-topos",
       "title": "Grothendieck topologies & topoi",
       "tier": "derived",
       "symbol": "topos"
      },
      {
       "id": "cat-higher",
       "title": "Higher & homotopical categories",
       "tier": "derived",
       "symbol": "∞cat"
      },
      {
       "id": "cat-applications",
       "title": "Categories in logic & computing",
       "tier": "derived",
       "symbol": "CHL"
      }
     ],
     "stats": "20 topics · 158 sub-topics"
    },
    {
     "id": "number-theory-roadmap",
     "nav": "Number theory",
     "title": "Primes, number fields & L-functions",
     "eyebrow": "Number theory roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "nt-divisibility",
       "title": "Divisibility & unique factorization",
       "tier": "elementary",
       "symbol": "gcd"
      },
      {
       "id": "nt-congruences",
       "title": "Congruences & modular arithmetic",
       "tier": "elementary",
       "symbol": "mod n"
      },
      {
       "id": "nt-quadratic-reciprocity",
       "title": "Quadratic reciprocity",
       "tier": "elementary",
       "symbol": "(a|p)"
      },
      {
       "id": "nt-diophantine",
       "title": "Diophantine equations",
       "tier": "elementary",
       "symbol": "Dioph"
      },
      {
       "id": "nt-continued-fractions",
       "title": "Continued fractions & approximation",
       "tier": "elementary",
       "symbol": "cfrac"
      },
      {
       "id": "nt-number-fields",
       "title": "Number fields & rings of integers",
       "tier": "algebraic",
       "symbol": "O_K"
      },
      {
       "id": "nt-ideal-factorization",
       "title": "Ideals, Dedekind domains & ramification",
       "tier": "algebraic",
       "symbol": "ideal"
      },
      {
       "id": "nt-class-group",
       "title": "The ideal class group",
       "tier": "algebraic",
       "symbol": "Cl(K)"
      },
      {
       "id": "nt-units",
       "title": "Units & the Dirichlet unit theorem",
       "tier": "algebraic",
       "symbol": "O_K^*"
      },
      {
       "id": "nt-local-fields",
       "title": "p-adic numbers & local fields",
       "tier": "algebraic",
       "symbol": "Q_p"
      },
      {
       "id": "nt-galois-nt",
       "title": "Galois theory of number fields",
       "tier": "algebraic",
       "symbol": "Frob"
      },
      {
       "id": "nt-cyclotomic",
       "title": "Cyclotomic fields",
       "tier": "algebraic",
       "symbol": "ζ_n"
      },
      {
       "id": "nt-arithmetic-functions",
       "title": "Arithmetic functions",
       "tier": "analytic",
       "symbol": "μ(n)"
      },
      {
       "id": "nt-dirichlet-series",
       "title": "Dirichlet series & Euler products",
       "tier": "analytic",
       "symbol": "Dser"
      },
      {
       "id": "nt-pnt",
       "title": "The prime number theorem",
       "tier": "analytic",
       "symbol": "PNT"
      },
      {
       "id": "nt-riemann-hypothesis",
       "title": "The Riemann hypothesis",
       "tier": "lfunctions",
       "symbol": "RH"
      },
      {
       "id": "nt-dirichlet-l",
       "title": "Dirichlet characters & L-functions",
       "tier": "lfunctions",
       "symbol": "L(s,χ)"
      },
      {
       "id": "nt-sieves",
       "title": "Sieve methods & prime gaps",
       "tier": "lfunctions",
       "symbol": "sieve"
      },
      {
       "id": "nt-class-field-theory",
       "title": "Class field theory",
       "tier": "modern",
       "symbol": "CFT"
      },
      {
       "id": "nt-elliptic-curves",
       "title": "Elliptic curves & modularity",
       "tier": "modern",
       "symbol": "E/Q"
      }
     ],
     "stats": "20 topics · 158 sub-topics"
    },
    {
     "id": "logic-roadmap",
     "nav": "Logic & set theory",
     "title": "Proof, models, sets & the limits of computation",
     "eyebrow": "Logic & set theory roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "log-propositional",
       "title": "Propositional logic",
       "tier": "logic",
       "symbol": "PROP"
      },
      {
       "id": "log-first-order",
       "title": "First-order logic",
       "tier": "logic",
       "symbol": "∀x"
      },
      {
       "id": "log-proof-systems",
       "title": "Proof systems",
       "tier": "logic",
       "symbol": "⊢"
      },
      {
       "id": "log-completeness",
       "title": "Gödel completeness & compactness",
       "tier": "logic",
       "symbol": "compl"
      },
      {
       "id": "log-lowenheim",
       "title": "Löwenheim–Skolem & the Skolem paradox",
       "tier": "model",
       "symbol": "LS"
      },
      {
       "id": "log-model-theory",
       "title": "Models & elementary equivalence",
       "tier": "model",
       "symbol": "model"
      },
      {
       "id": "log-quantifier-elimination",
       "title": "Quantifier elimination & decidable theories",
       "tier": "model",
       "symbol": "QE"
      },
      {
       "id": "log-zfc",
       "title": "ZFC & the cumulative hierarchy",
       "tier": "set",
       "symbol": "ZFC"
      },
      {
       "id": "log-ordinals",
       "title": "Ordinals & transfinite recursion",
       "tier": "set",
       "symbol": "ω"
      },
      {
       "id": "log-cardinals",
       "title": "Cardinals & cardinal arithmetic",
       "tier": "set",
       "symbol": "ℵ"
      },
      {
       "id": "log-choice",
       "title": "The axiom of choice & its equivalents",
       "tier": "set",
       "symbol": "AC"
      },
      {
       "id": "log-continuum",
       "title": "The continuum hypothesis",
       "tier": "set",
       "symbol": "CH"
      },
      {
       "id": "log-forcing",
       "title": "Forcing & independence",
       "tier": "set",
       "symbol": "force"
      },
      {
       "id": "log-large-cardinals",
       "title": "Large cardinals & consistency strength",
       "tier": "set",
       "symbol": "κ"
      },
      {
       "id": "log-computability",
       "title": "Computability & Church–Turing",
       "tier": "computability",
       "symbol": "TM"
      },
      {
       "id": "log-undecidability",
       "title": "Undecidability",
       "tier": "computability",
       "symbol": "halt"
      },
      {
       "id": "log-incompleteness",
       "title": "Gödel incompleteness",
       "tier": "incompleteness",
       "symbol": "Gödel"
      },
      {
       "id": "log-degrees",
       "title": "Turing degrees & the arithmetical hierarchy",
       "tier": "incompleteness",
       "symbol": "deg"
      }
     ],
     "stats": "18 topics · 139 sub-topics"
    },
    {
     "id": "optimization-roadmap",
     "nav": "Optimization",
     "title": "Convexity, duality & the algorithms that exploit them",
     "eyebrow": "Optimization roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "opt-formulation",
       "title": "Optimization problems",
       "tier": "foundations",
       "symbol": "min f"
      },
      {
       "id": "opt-convex-sets",
       "title": "Convex sets & separation",
       "tier": "foundations",
       "symbol": "conv"
      },
      {
       "id": "opt-convex-functions",
       "title": "Convex functions & subgradients",
       "tier": "foundations",
       "symbol": "cvx f"
      },
      {
       "id": "opt-optimality",
       "title": "Optimality conditions",
       "tier": "foundations",
       "symbol": "∇f=0"
      },
      {
       "id": "opt-lagrangian",
       "title": "Lagrange multipliers & KKT",
       "tier": "duality",
       "symbol": "KKT"
      },
      {
       "id": "opt-duality",
       "title": "Lagrangian duality",
       "tier": "duality",
       "symbol": "dual"
      },
      {
       "id": "opt-fenchel",
       "title": "Convex conjugacy & Fenchel duality",
       "tier": "duality",
       "symbol": "f*"
      },
      {
       "id": "opt-lp",
       "title": "Linear programming & polyhedra",
       "tier": "duality",
       "symbol": "LP"
      },
      {
       "id": "opt-simplex",
       "title": "The simplex method",
       "tier": "algorithms",
       "symbol": "splx"
      },
      {
       "id": "opt-interior-point",
       "title": "Interior-point methods",
       "tier": "algorithms",
       "symbol": "IPM"
      },
      {
       "id": "opt-conic",
       "title": "Conic, SOCP & semidefinite programming",
       "tier": "algorithms",
       "symbol": "SDP"
      },
      {
       "id": "opt-gradient",
       "title": "Gradient methods & rates",
       "tier": "algorithms",
       "symbol": "GD"
      },
      {
       "id": "opt-accelerated",
       "title": "Momentum & acceleration",
       "tier": "algorithms",
       "symbol": "Nest"
      },
      {
       "id": "opt-stochastic",
       "title": "Stochastic gradient methods",
       "tier": "algorithms",
       "symbol": "SGD"
      },
      {
       "id": "opt-proximal",
       "title": "Proximal & splitting methods",
       "tier": "algorithms",
       "symbol": "prox"
      },
      {
       "id": "opt-nonconvex",
       "title": "Nonconvex optimization",
       "tier": "modern",
       "symbol": "nonc"
      },
      {
       "id": "opt-integer",
       "title": "Integer & combinatorial programming",
       "tier": "modern",
       "symbol": "ILP"
      },
      {
       "id": "opt-matroid",
       "title": "Greedy, matroids & submodularity",
       "tier": "modern",
       "symbol": "greedy"
      }
     ],
     "stats": "18 topics · 141 sub-topics"
    },
    {
     "id": "algebraic-geometry-roadmap",
     "nav": "Algebraic geometry",
     "title": "From rings and ideals to schemes & Riemann–Roch",
     "eyebrow": "Algebraic geometry roadmap",
     "kind": "roadmap",
     "topics": [
      {
       "id": "ag-rings",
       "title": "Commutative rings & ideals",
       "tier": "commutative",
       "symbol": "R,I"
      },
      {
       "id": "ag-modules",
       "title": "Modules & exact sequences",
       "tier": "commutative",
       "symbol": "M"
      },
      {
       "id": "ag-noetherian",
       "title": "Noetherian rings & primary decomposition",
       "tier": "commutative",
       "symbol": "ACC"
      },
      {
       "id": "ag-localization",
       "title": "Localization & local rings",
       "tier": "commutative",
       "symbol": "R_p"
      },
      {
       "id": "ag-integral",
       "title": "Integral extensions & Noether normalization",
       "tier": "commutative",
       "symbol": "int"
      },
      {
       "id": "ag-dimension",
       "title": "Krull dimension & regularity",
       "tier": "commutative",
       "symbol": "dim"
      },
      {
       "id": "ag-nullstellensatz",
       "title": "The Nullstellensatz",
       "tier": "varieties",
       "symbol": "I(V)"
      },
      {
       "id": "ag-affine",
       "title": "Affine varieties & coordinate rings",
       "tier": "varieties",
       "symbol": "k[V]"
      },
      {
       "id": "ag-zariski",
       "title": "The Zariski topology",
       "tier": "varieties",
       "symbol": "Zar"
      },
      {
       "id": "ag-projective",
       "title": "Projective varieties",
       "tier": "varieties",
       "symbol": "Pⁿ"
      },
      {
       "id": "ag-singularities",
       "title": "Smoothness & singularities",
       "tier": "varieties",
       "symbol": "sing"
      },
      {
       "id": "ag-sheaves",
       "title": "Sheaves & the structure sheaf",
       "tier": "schemes",
       "symbol": "O_X"
      },
      {
       "id": "ag-spec",
       "title": "Spec & affine schemes",
       "tier": "schemes",
       "symbol": "Spec"
      },
      {
       "id": "ag-schemes",
       "title": "Schemes & morphisms",
       "tier": "schemes",
       "symbol": "schm"
      },
      {
       "id": "ag-properties",
       "title": "Properness, flatness & smoothness",
       "tier": "schemes",
       "symbol": "flat"
      },
      {
       "id": "ag-divisors",
       "title": "Divisors & line bundles",
       "tier": "cohomology",
       "symbol": "Pic"
      },
      {
       "id": "ag-cohomology",
       "title": "Sheaf cohomology",
       "tier": "cohomology",
       "symbol": "H^i"
      },
      {
       "id": "ag-riemann-roch",
       "title": "Riemann–Roch & Serre duality",
       "tier": "cohomology",
       "symbol": "R–R"
      }
     ],
     "stats": "18 topics · 141 sub-topics"
    }
   ]
  }
 ]
};
