import Rive from '../vector-replay/vendor/webgl2_advanced.js';
const $=id=>document.getElementById(id);let runtime,ready=false,last='',queued=false;const layers=[];
function edges(objects){const out=[];for(const o of objects){const c=o.slice(1,4);if(o[0]===0){for(let axis=0;axis<3;axis++)for(let j=0;j<48;j++){const p=t=>c.map((x,i)=>x+(i===(axis+1)%3?o[4]*Math.cos(t):i===(axis+2)%3?o[4]*Math.sin(t):0));out.push([p(j*Math.PI/24),p((j+1)*Math.PI/24)]);}}else if(o[0]===1){const p=k=>c.map((x,i)=>x+((k&(1<<i))?1:-1)*o[5+i]);for(let k=0;k<8;k++)for(let i=0;i<3;i++)if(!(k&(1<<i)))out.push([p(k),p(k|(1<<i))]);}}return out;}
function draw(){queued=false;if(!ready||document.hidden||!window.rivxHostVisible)return;const v=window.rivxSceneView;if(!v)return;const key=JSON.stringify([v.matrix,v.width,v.height,window.rivxGatePhase]);if(last===key)return;last=key;
 const M=v.matrix,project=p=>{const w=M[3]*p[0]+M[7]*p[1]+M[11]*p[2]+M[15];if(w<=.05)return null;return [(1+(M[0]*p[0]+M[4]*p[1]+M[8]*p[2]+M[12])/w)*500,(1-(M[1]*p[0]+M[5]*p[1]+M[9]*p[2]+M[13])/w)*350];};
 const guide=layers[0];let count=0;for(const [a,b]of edges(v.occluders)){const p=project(a),q=project(b);if(!p||!q||count>=guide.nodes.length)continue;const n=guide.nodes[count++],dx=q[0]-p[0],dy=q[1]-p[1];Object.assign(n,{x:p[0],y:p[1],rotation:Math.atan2(dy,dx),scaleX:Math.hypot(dx,dy),scaleY:.36});}for(let i=count;i<guide.nodes.length;i++){guide.nodes[i].scaleX=0;guide.nodes[i].scaleY=0;}
 layers[1].animation.time=(window.rivxGatePhase||0)*6.25;layers[1].animation.apply(1);
 for(const l of layers){if(l.canvas.width!==v.width||l.canvas.height!==v.height){l.canvas.width=v.width;l.canvas.height=v.height;}l.renderer.clear();l.renderer.save();l.renderer.align(runtime.Fit.fill,runtime.Alignment.center,{minX:0,minY:0,maxX:v.width,maxY:v.height},{minX:0,minY:0,maxX:1000,maxY:700});l.art.advance(0);l.art.draw(l.renderer);l.renderer.restore();l.renderer.flush();l.canvas.dataset.renderer='official-rive-webgl2';}guide.canvas.dataset.sceneGuides=count;document.body.dataset.rive='ready';
}
function wake(){if(ready&&!queued){queued=true;runtime.requestAnimationFrame(draw);}}
(async()=>{runtime=await Rive({locateFile:()=>new URL('../vector-replay/vendor/rive.wasm',import.meta.url).href});for(const [id,url]of [['riveUnderlay','../photon-studio/ink-pool.riv'],['riveOverlay','../../../live_demos/rivex/exports/retained-caustic-splats.overlay.riv']]){const canvas=$(id),renderer=runtime.makeRenderer(canvas),response=await fetch(url);if(!response.ok)throw Error('Rive layer missing: '+url);const file=await runtime.load(new Uint8Array(await response.arrayBuffer())),art=file.defaultArtboard(),layer={canvas,renderer,file,art};if(id==='riveUnderlay')layer.nodes=Array.from({length:384},(_,i)=>art.node('ink'+i));else layer.animation=new runtime.LinearAnimationInstance(art.animationByIndex(0),art);layers.push(layer);}ready=true;$('riveUnderStat').textContent='Scene guides: official Rive · projected native sphere and box';$('riveStat').textContent='Time marker: official Rive · shared arrival clock';window.addEventListener('rivx-view-updated',wake);wake();})().catch(e=>{$('riveUnderStat').textContent='Rive layer unavailable: '+e.message;document.body.dataset.riveError=e.message;console.error(e);});
window.addEventListener('pagehide',e=>{if(!e.persisted){ready=false;for(const l of layers){l.animation?.delete();l.art.delete();l.file.delete();l.renderer.delete();}}});window.addEventListener('pageshow',()=>{last='';wake();});
