(() => {
  'use strict';
  const C=299792458,TAU=2*Math.PI,wrap=x=>(x%TAU+TAU)%TAU;
  function signal(depth,extra,strength,fMHz,reference=0){const f=fMHz*1e6,p0=-TAU*f*2*depth/C,p1=-TAU*f*(2*depth+extra)/C,real=Math.cos(p0)+strength*Math.cos(p1),imag=Math.sin(p0)+strength*Math.sin(p1),rr=real*Math.cos(reference)-imag*Math.sin(reference),ri=real*Math.sin(reference)+imag*Math.cos(reference),B=1+strength,taps=[0,Math.PI/2,Math.PI,3*Math.PI/2].map(d=>B+.5*(rr*Math.cos(d)-ri*Math.sin(d))),xr=taps[0]-taps[2],xi=taps[3]-taps[1],re=xr*Math.cos(reference)+xi*Math.sin(reference),im=xi*Math.cos(reference)-xr*Math.sin(reference);return {p0,p1,real,imag,taps,B,amplitude:Math.hypot(re,im),depth:C*wrap(-Math.atan2(im,re))/(4*Math.PI*f),range:C/(2*f),rr,ri};}
  const math={C,wrap,signal};if(typeof module!=='undefined')module.exports=math;if(typeof document==='undefined')return;
  const {line,dot,arrow,setup}=ResearchLab;
  setup(({$,ctx,w,h})=>{
    const vals={};for(const id of ['depth','extra','strength','frequency','reference']){vals[id]=+$ (id).value;$(id+'-out').value=vals[id].toFixed(['frequency','reference'].includes(id)?0:2);}
    const {depth,extra,strength,frequency,reference}=vals,s=signal(depth,extra,strength,frequency,reference*Math.PI/180);$('depth-estimate').textContent=s.amplitude<1e-6?'undefined phase':s.depth.toFixed(3);$('amplitude').textContent=s.amplitude.toFixed(3);$('ambiguity').textContent=s.range.toFixed(3);
    const x=w*.27,y=h*.46,R=Math.min(w*.21,h*.31),scale=R/2.4;ctx.font='12px system-ui';ctx.fillStyle='#c9dbe0';ctx.fillText('Complex modulation plane',20,24);line(ctx,[[x-R,y],[x+R,y]],'#8297b03d');line(ctx,[[x,y-R],[x,y+R]],'#8297b03d');for(const r of [1,2]){ctx.beginPath();ctx.arc(x,y,scale*r,0,TAU);ctx.strokeStyle='#9ba8ce35';ctx.stroke();}
    const direct=[x+Math.cos(s.p0)*scale,y-Math.sin(s.p0)*scale],total=[x+s.real*scale,y-s.imag*scale];arrow(ctx,[x,y],direct,'#83ecd0',3);arrow(ctx,direct,total,'#bca0f4',3);arrow(ctx,[x,y],total,'#f0ca79',3);dot(ctx,total,'#ffe8a7',5);ctx.fillStyle='#83ecd0';ctx.fillText('Direct',20,h-65);ctx.fillStyle='#bca0f4';ctx.fillText('+ indirect',90,h-65);ctx.fillStyle='#f0ca79';ctx.fillText('= sensor sum',174,h-65);ctx.fillStyle='#c3c9d9';ctx.fillText('Vectors are calibrated to the same reference.',20,h-38);
    const gx=w*.53,gy=61,gw=w*.43,gh=h*.51,max=1.65*(1+strength);ctx.fillStyle='#d6deea';ctx.fillText('Four taps recover a sinusoidal correlation',gx,24);line(ctx,[[gx,gy],[gx,gy+gh],[gx+gw,gy+gh]],'#8297b060');const py=a=>gy+gh-a/max*gh;line(ctx,Array.from({length:161},(_,i)=>{const d=TAU*i/160;return[gx+gw*i/160,py(s.B+.5*(s.rr*Math.cos(d)-s.ri*Math.sin(d)))];}),'#f1cd84',2);
    s.taps.forEach((v,i)=>{const px=gx+i*gw/4;line(ctx,[[px,gy+gh],[px,py(v)]],'#bda2ef88',3);dot(ctx,[px,py(v)],'#baa3f1',5);ctx.fillStyle='#b9c3d6';ctx.fillText(i+'π/2',px-6,gy+gh+20);ctx.fillText(v.toFixed(2),px-8,py(v)-12);});
    const ly=gy+gh+67,cam=[gx,ly],surface=[gx+gw*.76,ly],bounce=[gx+gw*.40,ly+50];arrow(ctx,cam,surface,'#83ecd0');arrow(ctx,surface,[cam[0],cam[1]+8],'#83ecd07a');line(ctx,[surface,bounce,[cam[0],cam[1]+8]],'#bca0f4',2,[5,4]);dot(ctx,cam,'#f0ca79',4);dot(ctx,surface,'#84ecd0',5);dot(ctx,bounce,'#bca0f4',4);ctx.fillStyle='#b8c8d2';ctx.fillText('Camera',gx,ly-14);ctx.fillText('Surface',surface[0]-20,ly-14);ctx.fillText('extra path = '+extra.toFixed(2)+' m',gx+gw*.23,ly+69);
  });
})();
