// Image-space counterparts of the native space-time volume and ordered beam.
// Rive owns the source image. These programs are custom WebGL2, not GPU Canvas.
export function makeAdvanced(canvas, riveCanvas, runtime, extract, makeGaussianFit) {
 const gl=canvas.getContext('webgl2',{alpha:false,preserveDrawingBuffer:true});
 if(!gl)throw Error('WebGL2 is required.');
 const full=`#version 300 es
 precision highp float;out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0,1);}`;
 const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const programs=[];
 function program(f,v=full){const p=gl.createProgram(),a=shader(gl.VERTEX_SHADER,v),b=shader(gl.FRAGMENT_SHADER,f);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(a);gl.deleteShader(b);programs.push(p);return p;}
 function uniforms(p,values){gl.useProgram(p);for(const [name,v]of Object.entries(values)){const l=gl.getUniformLocation(p,name);if(Array.isArray(v)){if(v.length===2)gl.uniform2fv(l,v);else gl.uniform3fv(l,v);}else gl.uniform1f(l,v);}}
 function tex(unit,t,target=gl.TEXTURE_2D){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(target,t);}
 const textures=[],fb=gl.createFramebuffer();
 function texture(w,h,floating=false){const t=gl.createTexture();textures.push(t);tex(0,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,floating?gl.RGBA16F:gl.RGBA8,w,h,0,gl.RGBA,floating?gl.HALF_FLOAT:gl.UNSIGNED_BYTE,null);return t;}
 function target(t,w,h){gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,t,0);gl.viewport(0,0,w,h);}
 const source=texture(720,480);let previous=texture(256,256),previousReady=false;
 const floatBuffer=!!gl.getExtension('EXT_color_buffer_float');
 const beamBuffers=[texture(720,480,floatBuffer),texture(720,480,floatBuffer)],beamImage=texture(720,480);
 let beamIndex=0,beamClock=0,lastBeam=0,chain=[],chainLength=0,lastChain=-Infinity;
 const copy=program(`#version 300 es
 precision highp float;in vec2 uv;out vec4 color;uniform sampler2D source;uniform float decay;void main(){color=texture(source,uv)*decay;}`);
 const capture=program(`#version 300 es
 precision highp float;in vec2 uv;out vec4 color;uniform sampler2D source,prev;uniform float flip,first;void main(){vec2 p=mix(uv,vec2(uv.x,1.-uv.y),flip);vec3 c=texture(source,p).rgb;float m=first>.5?0.:clamp(length(c-texture(prev,uv).rgb)*30.,0.,1.);color=vec4(c,m);}`);
 gl.useProgram(capture);gl.uniform1i(gl.getUniformLocation(capture,'prev'),1);
 const ray=program(`#version 300 es
 precision highp float;precision highp sampler2DArray;
 in vec2 uv;out vec4 color;uniform sampler2DArray volume;uniform sampler2D source;
 uniform float layers,head,count,density,depth,steps,yaw,pitch,zoom,mode;
 float lum(vec3 c){return dot(c,vec3(.2126,.7152,.0722));}
 vec4 sampleVolume(vec3 p){float f=clamp(p.z,0.,1.)*(layers-1.);if(f>=count)return vec4(0);f=min(f,count-1.);float a=floor(f),b=min(a+1.,count-1.);float i=mod(head-a+layers,layers),j=mod(head-b+layers,layers);return mix(texture(volume,vec3(p.xy,i)),texture(volume,vec3(p.xy,j)),fract(f));}
 vec3 image(vec2 p){return texture(source,vec2(clamp(p.x,0.,1.),1.-clamp(p.y,0.,1.))).rgb;}
 float height(vec2 p){vec2 d=vec2(3./720.,3./480.);return .9*(lum(image(p))*.4+(lum(image(p+vec2(d.x,0)))+lum(image(p-vec2(d.x,0)))+lum(image(p+vec2(0,d.y)))+lum(image(p-vec2(0,d.y))))*.15);}
 void main(){vec3 ro=zoom*vec3(sin(yaw)*cos(pitch),sin(pitch),cos(yaw)*cos(pitch));vec3 fw=normalize(-ro),rt=normalize(cross(fw,vec3(0,1,0))),up=cross(rt,fw);vec2 q=(uv*2.-1.)*vec2(1.5,1.);vec3 rd=normalize(fw*2.7+rt*q.x+up*q.y);vec3 halfBox=vec3(1.5,1,depth);if(mode>2.5)halfBox=vec3(1.5,.7,1.);
 vec3 a=(-halfBox-ro)/rd,b=(halfBox-ro)/rd;vec3 lo=min(a,b),hi=max(a,b);float t0=max(max(lo.x,lo.y),lo.z),t1=min(min(hi.x,hi.y),hi.z);vec3 bg=vec3(.018,.034,.044)+.014*uv.y;vec4 acc=vec4(0);if(t1>max(t0,0.)){float dt=(t1-max(t0,0.))/steps;for(int i=0;i<192;i++){if(float(i)>=steps||acc.a>.992)break;vec3 pos=ro+rd*(max(t0,0.)+(float(i)+.5)*dt);vec3 p=pos/(2.*halfBox)+.5;vec3 c;float sigma;
 if(mode>2.5){vec2 xz=p.xz;float h=height(xz);float y=p.y;float band=exp(-pow((h-y)/.027,2.));vec2 d=vec2(2./720.,2./480.);vec3 n=normalize(vec3((height(xz-d.xy)-height(xz+d.xy))*18.,1.,(height(xz-d.yx)-height(xz+d.yx))*18.));float lit=.28+.72*max(0.,dot(n,normalize(vec3(-.5,1.,.6))));c=mix(vec3(.055,.23,.24),vec3(.86,.69,.36),clamp(h*1.4,0.,1.))*lit;sigma=density*band*4.;}
 else {vec4 v=sampleVolume(p);c=v.rgb;float l=lum(c);float weight=smoothstep(.045,.22,l);if(mode>.5&&mode<1.5)weight*=v.a;weight*=exp(-p.z*.5);if(mode>1.5){float d=abs(fract(l*9.+.5)-.5);weight*=1.-smoothstep(.025,.09,d);c=.5+.5*cos(6.28318*(l*.85+vec3(0,.33,.66)));}sigma=density*weight;}
 float alpha=1.-exp(-sigma*dt*4.);acc.rgb+=(1.-acc.a)*c*alpha;acc.a+=(1.-acc.a)*alpha;}}color=vec4(acc.rgb+(1.-acc.a)*bg,1);}`);
 gl.useProgram(ray);gl.uniform1i(gl.getUniformLocation(ray,'volume'),2);
 const beamVertex=`#version 300 es
 precision highp float;layout(location=0)in vec2 position;layout(location=1)in vec2 local;layout(location=2)in float len;layout(location=3)in float gain;out vec2 p;out float lengthPx,energy;void main(){p=local;lengthPx=len;energy=gain;gl_Position=vec4(position/vec2(360,240)-1.,0,1);}`;
 const beam=program(`#version 300 es
 precision highp float;in vec2 p;in float lengthPx,energy;out vec4 color;uniform float radius,strength;
 float erfA(float x){float s=sign(x);x=abs(x);float t=1.+.278393*x+.230389*x*x+.000972*x*x*x+.078108*x*x*x*x;return s*(1.-1./(t*t*t*t));}
 void main(){float sigma=max(radius,.3);float along=erfA(p.x/(1.414214*sigma))-erfA((p.x-lengthPx)/(1.414214*sigma));float E=max(0.,along)*exp(-p.y*p.y/(2.*sigma*sigma))*(strength*2.*sigma/max(lengthPx,sigma))*energy;color=vec4(vec3(E),0);}`,beamVertex);
 const displayBeam=program(`#version 300 es
 precision highp float;in vec2 uv;out vec4 color;uniform sampler2D source;void main(){float e=texture(source,uv).r;vec3 hue=vec3(.10,1.,.23);vec3 c=hue*(1.-exp(-3.2*e));c=mix(c,vec3(.78,1.,.79),smoothstep(1.6,4.,e));color=vec4(vec3(.002,.009,.004)+c,1);}`);
 const vao=gl.createVertexArray(),vbo=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);for(let i=0;i<4;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,i<2?2:1,gl.FLOAT,false,24,[0,8,16,20][i]);}gl.bindVertexArray(null);
 let adaptiveWidth=480,lastDraw=0,meanFrame=16,lastAdapt=0;let history=null,res=0,layers=0,head=0,count=0,lastCapture=-Infinity,stepCount=96;
 function allocate(quality){const r=quality==='studio'?512:256,n=quality==='studio'?128:64;stepCount=quality==='studio'?192:64;if(r===res)return;if(history)gl.deleteTexture(history);gl.deleteTexture(previous);previous=texture(r,r);previousReady=false;res=r;layers=n;history=gl.createTexture();tex(2,history,gl.TEXTURE_2D_ARRAY);gl.texStorage3D(gl.TEXTURE_2D_ARRAY,1,gl.RGBA8,res,res,layers);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D_ARRAY,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);count=0;head=0;lastCapture=-Infinity;}
 function captureFrame(image,flip,time,rate){const interval=1000/rate;if(time-lastCapture+1e-4<interval)return;head=count?(head+1)%layers:0;gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTextureLayer(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,history,0,head);gl.viewport(0,0,res,res);tex(0,image);tex(1,previous);uniforms(capture,{flip,first:previousReady?0:1});gl.drawArrays(gl.TRIANGLES,0,3);
 // Preserve the preceding RGB frame in a separate attachment; never sample a bound draw target.
 target(previous,res,res);tex(2,history,gl.TEXTURE_2D_ARRAY);tex(0,image);uniforms(capture,{flip,first:1});tex(1,source);gl.drawArrays(gl.TRIANGLES,0,3);count=Math.min(layers,count+1);lastCapture=Number.isFinite(lastCapture)?lastCapture+Math.floor((time-lastCapture+1e-4)/interval)*interval:time;previousReady=true;}
 function orderSegments(raw){
  // Link adjacent marching-square edges, then choose the nearest contour endpoint.
  const key=p=>p.map(x=>Math.round(x*100)).join(','),adj=new Map();raw.forEach((s,i)=>[s.a,s.b].forEach(p=>{const k=key(p);if(!adj.has(k))adj.set(k,[]);adj.get(k).push(i);}));const used=new Uint8Array(raw.length),paths=[];
  for(let i=0;i<raw.length;i++){if(used[i])continue;used[i]=1;const p=[raw[i].a,raw[i].b];for(let k=0;k<2;k++){while(true){const at=k?p[0]:p[p.length-1],next=(adj.get(key(at))||[]).find(j=>!used[j]);if(next===undefined)break;used[next]=1;const s=raw[next],other=key(s.a)===key(at)?s.b:s.a;k?p.unshift(other):p.push(other);}}paths.push(p);}
  chain=[];chainLength=0;let at=[360,240];while(paths.length){let best=0,reverse=false,dist=Infinity;for(let i=0;i<paths.length;i++)for(let end=0;end<2;end++){const p=paths[i][end?paths[i].length-1:0],d=(at[0]-p[0])**2+(at[1]-p[1])**2;if(d<dist){best=i;reverse=!!end;dist=d;}}const p=paths.splice(best,1)[0];if(reverse)p.reverse();const add=(a,b,gain)=>{const len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len>.01){chain.push({a:[a[0],480-a[1]],b:[b[0],480-b[1]],len,start:chainLength,gain});chainLength+=len;}};add(at,p[0],.012);for(let i=1;i<p.length;i++)add(p[i-1],p[i],1);at=p[p.length-1];}
 }
 function drawBeam(input,state,time){if(time-lastChain>220||!chain.length){orderSegments(extract(input,Math.min(state.density,22),state.strength));lastChain=time;}const dt=state.playing?(lastBeam?Math.min(.08,(time-lastBeam)/1000):1/60):0;lastBeam=time;const next=1-beamIndex;target(beamBuffers[next],720,480);tex(0,beamBuffers[beamIndex]);uniforms(copy,{decay:Math.exp(-dt/Math.max(.05,state.persistence))});gl.drawArrays(gl.TRIANGLES,0,3);
  const start=beamClock%Math.max(1,chainLength),distance=Math.min(chainLength,dt*chainLength*1.25);beamClock+=distance;const end=start+distance,verts=[],pad=state.radius*4;
  function emit(s,a,b){if(b<=a)return;const t0=(a-s.start)/s.len,t1=(b-s.start)/s.len,x=s.a[0]+(s.b[0]-s.a[0])*t0,y=s.a[1]+(s.b[1]-s.a[1])*t0,len=(t1-t0)*s.len,dx=(s.b[0]-s.a[0])/s.len,dy=(s.b[1]-s.a[1])/s.len;for(const [u,v]of [[-pad,-pad],[len+pad,-pad],[-pad,pad],[-pad,pad],[len+pad,-pad],[len+pad,pad]])verts.push(x+u*dx-v*dy,y+u*dy+v*dx,u,v,len,s.gain);}
  for(const s of chain){emit(s,Math.max(start,s.start),Math.min(end,s.start+s.len));if(end>chainLength)emit(s,s.start,Math.min(end-chainLength,s.start+s.len));}
  if(verts.length){uniforms(beam,{radius:state.radius,strength:state.strength*2.});gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,verts.length/6);gl.bindVertexArray(null);gl.disable(gl.BLEND);}beamIndex=next;
  target(beamImage,720,480);tex(0,beamBuffers[beamIndex]);gl.useProgram(displayBeam);gl.drawArrays(gl.TRIANGLES,0,3);
 }
 const sample=document.createElement('canvas');sample.width=96;sample.height=64;const sampleCtx=sample.getContext('2d',{willReadFrequently:true});let marks=[];
 const riveRenderer=runtime.makeRenderer(riveCanvas,false);let riveFile=null,riveArt=null,rivePending=false,lastRive=-Infinity,riveDisposed=false,poolPalette=null,poolNodes=[],poolVersion=0,restoredPalette=null;
 const splat=program(`#version 300 es
 precision highp float;in vec2 p;in vec3 rgb;out vec4 color;void main(){if(dot(p,p)>9.)discard;float alpha=.96*exp(-.5*dot(p,p));color=vec4(rgb*alpha,alpha);}`,`#version 300 es
 precision highp float;layout(location=0)in vec4 geom;layout(location=1)in vec4 tone;out vec2 p;out vec3 rgb;void main(){vec2 corners[6]=vec2[6](vec2(-3,-3),vec2(3,-3),vec2(-3,3),vec2(-3,3),vec2(3,-3),vec2(3,3));p=corners[gl_VertexID];float c=cos(tone.w),s=sin(tone.w);vec2 q=p*geom.zw;q=mat2(c,s,-s,c)*q+geom.xy;gl_Position=vec4(q/vec2(360.,240.)*vec2(1.,-1.)+vec2(-1.,1.),0,1);rgb=tone.rgb;}`);
 const splatVao=gl.createVertexArray(),splatVbo=gl.createBuffer();gl.bindVertexArray(splatVao);gl.bindBuffer(gl.ARRAY_BUFFER,splatVbo);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,4,gl.FLOAT,false,32,i*16);gl.vertexAttribDivisor(i,1);}gl.bindVertexArray(null);
 const fitter=makeGaussianFit(96,64);let fittingActive=false;
 function makeMarks(input,state){return marks;}
 function updateFit(input,state){sampleCtx.clearRect(0,0,96,64);sampleCtx.drawImage(input,0,0,96,64);fitter.setTarget(sampleCtx.getImageData(0,0,96,64).data,Number(state.fitCount)||192);const steps=state.fitRunning?fitter.advance(Number(state.fitBudget)||4):0;marks=fitter.marks;fittingActive=state.fitRunning&&steps>0&&fitter.stats.iteration<400;}
 function drawSplats(input,state){const data=[];for(const m of makeMarks(input,state))data.push(m.x,m.y,m.sx,m.sy,...m.c.map(c=>c/255),m.angle);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,720,480);gl.clearColor(.025,.057,.067,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.useProgram(splat);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.bindVertexArray(splatVao);gl.bindBuffer(gl.ARRAY_BUFFER,splatVbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.drawArraysInstanced(gl.TRIANGLES,0,6,data.length/8);gl.bindVertexArray(null);gl.disable(gl.BLEND);return data.length/8;}
 function layered(marks,draw){for(const m of marks){let opacity=0;for(let i=8;i>=1;i--){const radius=m.sigma*i*.375,desired=.96*Math.exp(-.5*((i-.5)*.375)**2),alpha=(desired-opacity)/(1-opacity);opacity=desired;draw(m,radius,alpha);}}}
 function nearest(c,palette,used=null){let best=-1,d=Infinity;for(let i=0;i<palette.length;i++){if(used&&used[i]>=palette[i].slots)continue;const p=palette[i].c,v=(c[0]-p[0])**2+(c[1]-p[1])**2+(c[2]-p[2])**2;if(v<d){d=v;best=i;}}return best;}
 function paletteFor(marks){const colors=marks.map(m=>m.c);if(!colors.length)colors.push([100,150,130]);const palette=[{c:colors[0]}];while(palette.length<24){let far=0,best=null;for(const c of colors){const p=palette[nearest(c,palette)].c,d=c.reduce((a,x,i)=>a+(x-p[i])**2,0);if(d>far){far=d;best=c;}}if(far<30)break;palette.push({c:best.slice()});}for(let pass=0;pass<5;pass++){const sums=palette.map(()=>[0,0,0,0]);for(const c of colors){const sum=sums[nearest(c,palette)];for(let i=0;i<3;i++)sum[i]+=c[i];sum[3]++;}palette.forEach((p,i)=>{if(sums[i][3])p.c=sums[i].slice(0,3).map(v=>Math.round(v/sums[i][3]));p.count=sums[i][3];});}const free=Math.min(768,Math.max(192,Math.ceil(colors.length*1.4)))-palette.length*3;palette.forEach(p=>p.slots=3+Math.floor(free*p.count/colors.length));return palette;}
 function drawRive(input,state,time){const marks=makeMarks(input,state);if(!poolPalette&&!rivePending){poolPalette=restoredPalette||paletteFor(marks);restoredPalette=null;const version=++poolVersion,palette=poolPalette;rivePending=true;runtime.load(packRive(input,state,palette),undefined,false).then(next=>{if(riveDisposed||version!==poolVersion){next?.delete();return;}const board=next.defaultArtboard();riveArt?.delete();riveFile?.delete();riveFile=next;riveArt=board;poolNodes=palette.map((p,i)=>Array.from({length:p.slots},(_,j)=>board.node('splat-'+i+'-'+j)));}).finally(()=>rivePending=false);}if(riveArt&&poolNodes.length){for(const group of poolNodes)for(const n of group)n.scaleX=n.scaleY=0;const used=poolPalette.map(()=>0);for(const m of marks){const i=nearest(m.c,poolPalette,used);if(i<0)break;const n=poolNodes[i][used[i]++];n.x=m.x;n.y=m.y;n.scaleX=m.sx;n.scaleY=m.sy;n.rotation=m.angle;}riveArt.advance(0);riveRenderer.clear();riveArt.draw(riveRenderer);riveRenderer.flush();return used.reduce((a,b)=>a+b,0)*8;}return 0;}
 function packRive(input,state,palette=null,creditText=''){const props={4:1,5:0,7:2,8:2,13:2,14:2,15:2,18:2,20:2,21:2,37:3,40:0},bytes=[82,73,86,69],u=n=>{while(n>=128){bytes.push((n&127)|128);n>>>=7;}bytes.push(n);},raw=new ArrayBuffer(4),dv=new DataView(raw),four=(n,isFloat)=>{isFloat?dv.setFloat32(0,n,true):dv.setUint32(0,n,true);bytes.push(...new Uint8Array(raw));};[7,0,0].forEach(u);Object.keys(props).forEach(x=>u(+x));u(0);const types=Object.values(props);for(let i=0;i<types.length;i+=4)four(types.slice(i,i+4).reduce((a,x,j)=>a|(x<<(j*2)),0));function obj(t,p={}){u(t);for(const[k,v]of Object.entries(p)){u(+k);switch(props[k]){case 0:u(v);break;case 1:{const b=new TextEncoder().encode(v);u(b.length);bytes.push(...b);break;}case 2:four(v,true);break;case 3:four(v);}}u(0);}obj(23);obj(1,{4:'Layered Rive splat snapshot'+(creditText?' — '+creditText:''),7:720,8:480});let id=1;if(palette){const rings=[];layered([{sigma:1}],(_,r,a)=>rings.push({r,a}));for(let i=0;i<palette.length;i++)for(let j=0;j<palette[i].slots;j++){const group=id++;obj(2,{4:'splat-'+i+'-'+j,5:0,13:-9999,14:-9999});for(const {r,a}of rings){obj(3,{5:group,18:a});obj(4,{5:id,20:r*2,21:r*2});obj(20,{5:id,40:2});const c=palette[i].c;obj(18,{5:id+2,37:((255<<24)|(c[0]<<16)|(c[1]<<8)|c[2])>>>0});id+=4;}}return new Uint8Array(bytes);}const layers=[];layered(makeMarks(input,state),(m,r,a)=>layers.push({m,r,a}));for(const {m,r,a}of layers){obj(3,{5:0,13:m.x,14:m.y,15:m.angle,18:a});obj(4,{5:id,20:r*2,21:r*2*m.sy/m.sx});obj(20,{5:id,40:2});obj(18,{5:id+2,37:((255<<24)|(m.c[0]<<16)|(m.c[1]<<8)|m.c[2])>>>0});id+=4;}return new Uint8Array(bytes);}
 async function compress(bytes){const zipped=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());let str='';for(let i=0;i<zipped.length;i+=32768)str+=String.fromCharCode(...zipped.subarray(i,i+32768));return btoa(str);}
 async function decompress(text){const z=Uint8Array.from(atob(text),c=>c.charCodeAt(0));return new Response(new Blob([z]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}
 async function snapshot(){let volume=null,phosphor=null;if(history&&count){const bytes=new Uint8Array(res*res*4*count);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);for(let i=0;i<count;i++){gl.framebufferTextureLayer(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,history,0,i);gl.readPixels(0,0,res,res,gl.RGBA,gl.UNSIGNED_BYTE,bytes.subarray(i*res*res*4,(i+1)*res*res*4));}gl.bindFramebuffer(gl.FRAMEBUFFER,null);volume={res,layers,head,count,gzip:await compress(bytes)};}if(lastBeam){target(beamBuffers[beamIndex],720,480);const data=floatBuffer?new Float32Array(720*480*4):new Uint8Array(720*480*4);gl.readPixels(0,0,720,480,gl.RGBA,floatBuffer?gl.FLOAT:gl.UNSIGNED_BYTE,data);gl.bindFramebuffer(gl.FRAMEBUFFER,null);phosphor={float:floatBuffer,clock:beamClock,gzip:await compress(data)};}return {volume,phosphor,palette:poolPalette,fit:fitter.snapshot()};}
 async function restore(data){if(!data)return;fitter.restore(data.fit);restoredPalette=data.palette||null;if(data.volume){const d=data.volume;allocate(d.res===512?'studio':'balanced');const bytes=new Uint8Array(await decompress(d.gzip));if(bytes.length!==res*res*4*d.count)throw Error('History payload size mismatch');tex(2,history,gl.TEXTURE_2D_ARRAY);gl.texSubImage3D(gl.TEXTURE_2D_ARRAY,0,0,0,0,res,res,d.count,gl.RGBA,gl.UNSIGNED_BYTE,bytes);head=d.head;count=d.count;}if(data.phosphor){const d=data.phosphor,raw=await decompress(d.gzip);let values=d.float?new Float32Array(raw):new Uint8Array(raw);if(d.float&&!floatBuffer)values=Uint8Array.from(values,x=>Math.min(255,Math.max(0,Math.round(x*255))));if(!d.float&&floatBuffer)values=Float32Array.from(values,x=>x/255);tex(0,beamBuffers[beamIndex]);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,720,480,gl.RGBA,floatBuffer?gl.FLOAT:gl.UNSIGNED_BYTE,values);beamClock=d.clock;}}
 return {draw(input,state,time){const volumeMode=['time','motion','iso','stm','beam-volume'].includes(state.preset),now=performance.now();if(lastDraw&&state.playing)meanFrame=meanFrame*.9+Math.min(100,now-lastDraw)*.1;lastDraw=now;if(volumeMode&&state.quality!=='studio'&&now-lastAdapt>800&&state.playing){if(meanFrame>21)adaptiveWidth=Math.max(288,Math.round(adaptiveWidth*.8/12)*12);else if(meanFrame<13)adaptiveWidth=Math.min(600,Math.round(adaptiveWidth*1.1/12)*12);lastAdapt=now;}const w=volumeMode&&state.quality!=='studio'?adaptiveWidth:720;if(canvas.width!==w){canvas.width=w;canvas.height=w*2/3;}tex(0,source);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,input);let shapes=0;if(['splats','rive-splats'].includes(state.preset))updateFit(input,state);if(state.preset==='rive-splats'){shapes=drawRive(input,state,time);return {shapes,history:count,fit:fitter.stats,fitRunning:fittingActive};}if(state.preset==='splats')return {shapes:drawSplats(input,state),history:count,fit:fitter.stats,fitRunning:fittingActive};
 const isBeam=state.preset.startsWith('beam');if(isBeam)drawBeam(input,state,time);if(state.preset==='beam'){gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,720,480);tex(0,beamImage);uniforms(copy,{decay:1});gl.drawArrays(gl.TRIANGLES,0,3);return {segments:chain.length,history:count,floatBuffer};}
 allocate(state.quality);if(state.playing||!count)captureFrame(isBeam?beamImage:source,isBeam?0:1,time,state.captureRate);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);tex(0,source);tex(2,history,gl.TEXTURE_2D_ARRAY);uniforms(ray,{layers,head,count,density:state.strength*3,depth:state.depth,steps:stepCount,yaw:state.yaw,pitch:state.pitch,zoom:state.zoom,mode:{motion:1,iso:2,stm:3}[state.preset]||0});gl.drawArrays(gl.TRIANGLES,0,3);return {history:count,res,layers,steps:stepCount,outputWidth:canvas.width,segments:isBeam?chain.length:0};},clear(){count=0;lastCapture=-Infinity;lastChain=-Infinity;lastRive=-Infinity;lastBeam=0;beamClock=0;previousReady=false;for(const t of beamBuffers){target(t,720,480);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);},snapshot,restore,packRive,fitResidual:()=>fitter.residual(),resetFit(){fitter.reset();},resetSource(){fitter.reset();poolVersion++;poolPalette=null;restoredPalette=null;poolNodes=[];riveArt?.delete();riveFile?.delete();riveArt=riveFile=null;},dispose(){textures.forEach(t=>gl.deleteTexture(t));if(history)gl.deleteTexture(history);programs.forEach(p=>gl.deleteProgram(p));gl.deleteFramebuffer(fb);gl.deleteBuffer(vbo);gl.deleteVertexArray(vao);gl.deleteBuffer(splatVbo);gl.deleteVertexArray(splatVao);riveDisposed=true;riveArt?.delete();riveFile?.delete();riveRenderer.delete();}};
}
