document.documentElement.classList.toggle('embedded',parent!==window);
const embedded=window.__RIVX_EFFECT_BUNDLE__;
const dataModule=text=>'data:text/javascript;base64,'+encode64(new TextEncoder().encode(text));
const {default:Rive}=await import(embedded?dataModule(embedded.runtimeSource):'../vector-replay/vendor/webgl2_advanced.js');
const {makeEffects}=await import(embedded?dataModule(embedded.effectsSource):'./effects.js');
const {makeAdvanced}=await import(embedded?dataModule(embedded.advancedSource):'./advanced.js');
const {makeGaussianFit}=await import(embedded?dataModule(embedded.fittingSource):'./fitting.js');
const {makeLens}=await import(embedded?dataModule(embedded.lensSource):'./lens.js');
const $=id=>document.getElementById(id),controls=[...document.querySelectorAll('button,input,select')];controls.forEach(c=>c.disabled=true);
const descriptions={ink:'Luminance isolines, diagonal hatching and edges make a copper engraving. This shader shades pixels; Extracted contours exports actual paths.',oil:'A four-quadrant Kuwahara filter chooses the neighborhood with the lowest color variance. Its edge-preserving patches and a subtle canvas texture form the oil-paint treatment.',splats:'A progressive optimizer changes Gaussian position, covariance and RGB to reduce reconstruction MSE. Every accepted step improves the current target. Freeze the source to inspect convergence, or animate with a warm start. This is bounded 2D fitting; no 3D scene is learned.', 'rive-splats':'The optimized image becomes actual ordinary Rive geometry: eight translucent ellipse layers per Gaussian. The live pool uses a bounded palette; Export fitted geometry saves the current full-colour static geometry in a vanilla .riv. Animation and optical processing remain in the hybrid HTML.',beam:'Marching-square segments are joined into contours, then traversed in nearest-endpoint order. A Gaussian beam integrates along the moving segment; a persistent energy buffer decays exponentially. Travel between contours has very low intensity.',time:'A real x/y/time texture stack, raymarched front-to-back with Beer–Lambert opacity. The newest frame is at one end of the volume. Orbit around it to inspect the recent animation.',motion:'The time volume uses differences between consecutive captured images as density. Stationary background falls away and animated strokes leave a three-dimensional motion sculpture.',iso:'Luminance level sets select thin sheets through the image history. These are colored scalar-field iso-bands inside the x/y/time volume, not physical object surfaces.',stm:'The current Rive image becomes a blurred luminance height field. Raymarching a thin shell around that height gives a lit relief. This is the native STM idea using image luminance; no scene depth is inferred.', 'beam-volume':'The persistent beam image becomes the input to the time stack. Orbit the accumulated x/y/time volume; both the path traversal and phosphor history affect its structure.',curves:'Marching squares turns a 240 ×160 luminance field into explicit contour segments. The SVG export contains those paths.',source:'The custom stage passes through the official Rive image for comparison.'};
const sources={
 truck:{file:'samples/truck.riv',name:'truck.riv',animation:'s:0',credit:'Truck · Rive official rive-wasm example · MIT repository license',url:'https://github.com/rive-app/rive-wasm/tree/master/wasm/examples/parcel_example'},
 faux:{file:'samples/faux.riv',name:'faux.riv',animation:'a:0',credit:'Faux 3D Game Icons · rishi.kumar.id · CC BY · Rive animation',url:'https://rive.app/marketplace/14514-27371-faux-3d-game-icons/'},
 planets:{file:'samples/planets.riv',name:'planets.riv',artboard:9,animation:'s:0',credit:'Planets · Rive renderer repository sample · original artist not identified in fixture metadata',url:'https://github.com/rive-app/rive-runtime/blob/main/renderer/webgpu_player/rivs/planets.riv'},
 jellyfish:{file:'samples/jellyfish.riv',name:'jellyfish.riv',animation:'a:11',credit:'Jellyfish · Rive runtime test fixture · original artist not identified in fixture metadata',url:'https://github.com/rive-app/rive-runtime/blob/main/tests/unit_tests/assets/jellyfish_test.riv'},
 rosette:{file:'kinetic-rosette.riv',name:'kinetic-rosette.riv',credit:'Kinetic rosette · original sample authored for this workshop'},
 glass:{file:'../../../live_demos/rivex/scene3d_orbit.riv',name:'scene3d_orbit.riv',credit:'600-angle glass · authored RIVX scene, exported as ordinary Rive'}
};
const showcases={
 'truck-beam':{source:'truck',preset:'beam',density:20,strength:1.7,persistence:1.1,radius:1.0},
 'faux-oil':{source:'faux',preset:'oil',density:48,strength:1.4},
 'faux-splats':{source:'faux',artboard:10,preset:'splats',density:60,strength:.72},
 'faux-rive':{source:'faux',artboard:10,preset:'rive-splats',density:60,strength:.72},
 'jellyfish-time':{source:'jellyfish',preset:'time',strength:1.2,yaw:.8,pitch:.3,depth:1.5},
 'planets-beam':{source:'planets',preset:'beam',density:24,strength:1.7,persistence:1.1,radius:1.0}
};
let sourceKey='truck',sourceCredit=null,boardIndex=0;
const state={preset:'beam',density:33,strength:.9,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,quality:'balanced',captureRate:60,depth:.8,persistence:.65,radius:1.2,yaw:.55,pitch:.28,zoom:3.9,fitCount:192,fitBudget:4,fitRunning:true,lensEnabled:false,lensMode:'glass',lensX:.52,lensY:.48,lensRadius:.27,lensIor:1.5,lensDispersion:.07,lensContent:false,...embedded?.settings};
const advancedModes=new Set(['splats','rive-splats','beam','beam-volume','time','motion','iso','stm']);
let runtime,renderer,effects,advanced,lens,file,art,anim,machine,sourceBytes,sourceName='kinetic-rosette.riv',sourceMeta=null,ready=false,raf=0,last=0,frame=0,visible=true,hostPaused=false,needsPresent=2,loadVersion=0,exporting=false,elapsed=0,fpsFrames=0,fpsTime=0,fitActive=false;
const fail=e=>{$('error').hidden=false;$('error').textContent=e.message||String(e);console.error(e);};
function decode64(text){return Uint8Array.from(atob(text),c=>c.charCodeAt(0));}
function encode64(bytes){let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out);}
const isFit=()=>['splats','rive-splats'].includes(state.preset);
const isVolume=()=>['time','motion','iso','stm','beam-volume'].includes(state.preset);
function refresh(){document.querySelectorAll('[data-showcase]').forEach(b=>{const v=showcases[b.dataset.showcase];b.setAttribute('aria-pressed',String(v.source===sourceKey&&v.preset===state.preset));});for(const id of ['preset','density','strength','quality','depth','persistence','radius'])$(id).value=state[id];$('capture-rate').value=state.captureRate;$('density-value').textContent=state.density;$('play').textContent=state.playing?'Pause':'Play';$('effect-name').textContent=$('preset').selectedOptions[0].textContent;$('explanation').textContent=descriptions[state.preset];$('volume-controls').hidden=!isVolume();$('beam-controls').hidden=!state.preset.startsWith('beam');$('output-owner').textContent=state.preset==='rive-splats'?'02 / Official Rive vectors':state.preset==='curves'?'02 / Extracted paths':'02 / Custom WebGL2';refreshTools();}
function refreshTools(){
 $('fit-controls').hidden=!isFit();$('riv-snapshot').disabled=!isFit();for(const id of ['density','strength'])$(id).closest('label').hidden=isFit();$('clear-history').hidden=isFit();$('fit-count').value=state.fitCount;$('fit-budget').value=state.fitBudget;$('fit-toggle').textContent=state.fitRunning?'Pause fitting':'Resume fitting';
 for(const [id,key]of [['lens-enabled','lensEnabled'],['lens-content','lensContent']])$(id).checked=state[key];for(const [id,key]of [['lens-mode','lensMode'],['lens-radius','lensRadius'],['lens-ior','lensIor'],['lens-dispersion','lensDispersion']])$(id).value=state[key];$('lens').hidden=!state.lensEnabled;
 const route=state.preset==='rive-splats'?'Output: ordinary Rive ellipse geometry; the static .riv snapshot preserves full sampled colour.':state.preset==='curves'?'Output: explicit image-derived contour paths; SVG preserves their geometry.':isVolume()?'Output: custom GPU image/history volume; hybrid HTML preserves the running process.':'Output: custom GPU image processing; hybrid HTML preserves the running process.';
 $('capability-note').textContent=`${sourceKey==='import'?'Your imported .riv':'The selected .riv'} supplies rendered colour and supported timeline/state-machine interaction. All effects here accept that image; native object IDs, surface normals, depth and hidden surfaces are unavailable. ${route}${state.lensEnabled?' The added lens is a custom image-space layer and is retained in hybrid HTML.':''}`;
}

function wake(){if(ready&&!raf&&visible&&!hostPaused&&!document.hidden)raf=runtime.requestAnimationFrame(tick);}
function invalidate(){needsPresent=2;wake();}
function clear(){effects.clear();advanced.clear();}
function bounds(){return sourceMeta?.bounds||art.bounds;}
function drawSource(dt){if(anim){if(state.playing)anim.advance(dt);anim.apply(1);}if(machine)machine.advance(state.playing?dt:0);art.advance(state.playing?dt:0);renderer.clear();renderer.save();renderer.align(runtime.Fit.contain,runtime.Alignment.center,{minX:0,minY:0,maxX:720,maxY:480},bounds());art.draw(renderer);renderer.restore();renderer.flush();}
function tick(t){raf=0;if(!visible||hostPaused||document.hidden){last=0;return;}const dt=last?Math.min(.08,(t-last)/1000):0;last=t;if(state.playing)elapsed+=dt;
 // Official offscreen drawing is presented at the end of Rive's RAF. Consume the
 // preceding presented image before producing the next source image.
 if(frame>0){let r;if(advancedModes.has(state.preset)){r=advanced.draw($('source'),state,elapsed*1000);for(const id of ['effect','curves'])$(id).hidden=true;$('advanced').hidden=state.preset==='rive-splats';$('rive-output').hidden=state.preset!=='rive-splats';}else{r=effects.draw($('source'),state,t);$('advanced').hidden=$('rive-output').hidden=true;}
 fitActive=!!r.fitRunning;if(r.fit){const f=r.fit;document.body.dataset.fitLoss=f.loss;document.body.dataset.fitInitial=f.initialLoss;document.body.dataset.fitIteration=f.iteration;document.body.dataset.fitEpoch=f.epoch;document.body.dataset.fitAccepted=f.accepted;document.body.dataset.fitCount=f.count;$('fit-status').textContent=`MSE ${f.loss.toFixed(6)} · start ${f.initialLoss.toFixed(6)} · ${f.iteration} steps / ${f.accepted} accepted · ${f.count} Gaussians · ${f.milliseconds.toFixed(1)} ms last batch`;const residual=advanced.fitResidual();$('fit-residual').getContext('2d').putImageData(new ImageData(residual.pixels,residual.width,residual.height),0,0);}if(state.lensEnabled){const selected=state.preset==='rive-splats'?$('rive-output'):advancedModes.has(state.preset)?$('advanced'):state.preset==='curves'?$('curves'):$('effect');lens.draw(selected,state);}document.body.dataset.lens=state.lensEnabled?state.lensMode:'off';
 document.body.dataset.segments=r.segments||0;document.body.dataset.history=r.history||0;document.body.dataset.shapes=r.shapes||0;document.body.dataset.stackResolution=r.res||0;document.body.dataset.marchSteps=r.steps||0;
 const detail=r.res?`${r.res}² × ${r.history}/${r.layers} frames · ${r.steps} steps · ${r.outputWidth}px output · x / y / time`:r.shapes?`${r.shapes.toLocaleString()} ${state.preset==='rive-splats'?'ordinary ellipse draws':'Gaussian marks'}`:r.segments?`${r.segments.toLocaleString()} extracted segments`:'Live image processing';
 if(!state.playing&&!fitActive)$('metrics').textContent=detail+' · paused preview';
 if(t-fpsTime>500){document.body.dataset.measuredFps=(fpsFrames*1000/Math.max(1,t-fpsTime)).toFixed(1);$('metrics').textContent=`${detail}${state.playing||fitActive?' · '+(fpsFrames*1000/Math.max(1,t-fpsTime)).toFixed(0)+' presented fps':' · paused preview'}${sourceMeta?' · source: 600 distinct angles / 60 fps timeline':''}`;fpsFrames=0;fpsTime=t;}
 }drawSource(dt);fpsFrames++;document.body.dataset.frames=String(++frame);document.body.dataset.preset=state.preset;document.body.dataset.animationTime=anim?.time||0;if(anim){$('seek').max=String(Math.max(.01,anim.duration/anim.fps));$('seek').value=String(anim.time);$('seek-value').textContent=sourceMeta?((anim.time*36)%360).toFixed(1)+'°':anim.time.toFixed(2)+' s';}needsPresent--;if((state.playing&&(anim||machine||state.preset.startsWith('beam')||isVolume()))||fitActive||needsPresent>0)wake();}
function chooseAnimation(value){anim?.delete();machine?.delete();anim=machine=null;$('machine-inputs').replaceChildren();$('machine-inputs').hidden=true;const [kind,index]=String(value).split(':');if(kind==='s'){const def=art.stateMachineByIndex(+index);if(def){machine=new runtime.StateMachineInstance(def,art);const host=$('machine-inputs');host.hidden=false;for(let i=0;i<machine.inputCount();i++){const item=machine.input(i),label=document.createElement('label');label.textContent=item.name;const input=document.createElement(item.type===runtime.SMIInput.trigger?'button':'input');if(item.type===runtime.SMIInput.trigger){input.textContent='Fire';input.onclick=()=>{item.asTrigger().fire();invalidate();};}else{const typed=item.type===runtime.SMIInput.bool?item.asBool():item.asNumber();input.dataset.machineName=item.name;input.type=item.type===runtime.SMIInput.bool?'checkbox':'number';if(input.type==='checkbox')input.checked=typed.value;else{input.value=typed.value;input.step='any';}input.oninput=()=>{typed.value=input.type==='checkbox'?input.checked:+input.value;invalidate();};}label.append(input);host.append(label);}}}else{const def=art.animationByIndex(Number(index??value));if(def)anim=new runtime.LinearAnimationInstance(def,art);}last=0;clear();invalidate();}
function showCredit(){const el=$('source-credit');el.replaceChildren();if(sourceCredit?.url){const a=document.createElement('a');a.href=sourceCredit.url;a.target='_blank';a.rel='noopener';a.textContent=sourceCredit.credit;el.append(a);}else el.textContent=sourceCredit?.credit||'Your imported Rive document · no upload';$('source-choice').value=sourceKey;}
function setBoard(index,playback=null){anim?.delete();machine?.delete();art?.delete();anim=machine=null;art=file.artboardByIndex(index);boardIndex=index;$('artboard').value=String(index);$('animation').replaceChildren();let first='';for(const[kind,n,get]of [['a',art.animationCount(),i=>art.animationByIndex(i)],['s',art.stateMachineCount(),i=>art.stateMachineByIndex(i)]])for(let i=0;i<n;i++){const o=document.createElement('option');o.value=kind+':'+i;o.textContent=(kind==='s'?'State machine · ':'Timeline · ')+get(i).name;$('animation').append(o);if(!first)first=o.value;}if(!first){const o=document.createElement('option');o.value='a:-1';o.textContent='Static artboard';$('animation').append(o);}$('animation').disabled=!first;const choice=[...$('animation').options].some(o=>o.value===playback)?playback:first||'a:-1';$('animation').value=choice;advanced.resetSource();chooseAnimation(choice);if(anim&&sourceMeta)anim.time=8.;$('seek-row').hidden=!anim;$('status').textContent=`Official Rive · ${(sourceBytes.length/1048576).toFixed(1)} MB · ${sourceMeta?'600 angles · 60 fps':art.animationCount()+' timelines / '+art.stateMachineCount()+' machines'}`;$('timeline-note').textContent=sourceMeta?'600 distinct angle poses · 60 fps authored timeline':'Choose a timeline, or use state-machine inputs and pointer interaction.';}
async function load(bytes,name,meta=null,options={}){const version=++loadVersion,next=await runtime.load(bytes,undefined,false);if(!next)throw Error('The official runtime could not load this Rive file.');if(!next.artboardCount()){next.delete();throw Error('No artboard found.');}if(version!==loadVersion){next.delete();return;}anim?.delete();machine?.delete();art?.delete();file?.delete();anim=machine=art=null;file=next;sourceBytes=bytes;sourceName=name;sourceMeta=meta;sourceKey=options.key||'import';sourceCredit=options.credit||null;$('artboard').replaceChildren();for(let i=0;i<file.artboardCount();i++){const a=file.artboardByIndex(i),o=document.createElement('option');o.value=String(i);o.textContent=a.name;a.delete();$('artboard').append(o);}$('source-name').textContent=name;setBoard(Math.min(options.artboard||0,file.artboardCount()-1),options.animation);showCredit();$('error').hidden=true;document.body.dataset.source=name;document.body.dataset.ready='true';refresh();}
async function selectSource(key){if(embedded&&key===embedded.sourceKey){await load(decode64(embedded.sourceBase64),embedded.sourceName,embedded.sourceMeta,{key,credit:embedded.sourceCredit,artboard:embedded.boardIndex,animation:embedded.animation});return;}if(embedded&&key!=='rosette')throw Error('This exported player contains its selected source. Use Load .riv for another file.');const def=sources[key];if(!def)return;$('status').textContent='Loading '+def.name+'…';const bytes=embedded&&key==='rosette'?decode64(embedded.sampleBase64):new Uint8Array(await(await fetch(def.file)).arrayBuffer());const meta=key==='glass'?await(await fetch('glass-meta.json')).json():null;await load(bytes,def.name,meta,{key,credit:def,artboard:def.artboard,animation:def.animation});}
$('source-choice').onchange=()=>selectSource($('source-choice').value).catch(fail);$('artboard').onchange=()=>setBoard(+$('artboard').value);
for(const button of document.querySelectorAll('[data-showcase]'))button.onclick=async()=>{try{const preset=showcases[button.dataset.showcase];Object.assign(state,preset);state.playing=true;await selectSource(preset.source);if(preset.artboard!==undefined)setBoard(preset.artboard);refresh();invalidate();}catch(e){fail(e);}};
$('file').onchange=async()=>{const f=$('file').files?.[0];if(!f)return;try{if(f.size>64*1024*1024)throw Error('This study accepts files up to 64 MB.');await load(new Uint8Array(await f.arrayBuffer()),f.name);}catch(e){fail(e);}};
$('sample').onclick=()=>selectSource('rosette').catch(fail);
$('glass').onclick=()=>selectSource('glass').catch(fail);
$('seek').oninput=()=>{if(anim){anim.time=+$('seek').value;clear();invalidate();}};
$('animation').onchange=()=>{chooseAnimation($('animation').value);$('seek-row').hidden=!anim;};$('play').onclick=()=>{state.playing=!state.playing;last=0;refresh();invalidate();};
for(const id of ['preset','density','strength','quality','depth','persistence','radius','capture-rate'])$(id).oninput=()=>{const old=state.preset;const key=id==='capture-rate'?'captureRate':id;state[key]=['preset','quality'].includes(id)?$(id).value:Number($(id).value);if(id==='quality'||(id==='preset'&&!(isVolume()&&['time','motion','iso','stm','beam-volume'].includes(old)&&old.startsWith('beam')===state.preset.startsWith('beam'))))clear();refresh();invalidate();};
$('fit-toggle').onclick=()=>{state.fitRunning=!state.fitRunning;refresh();invalidate();};$('fit-reset').onclick=()=>{state.playing=false;state.fitRunning=true;advanced.resetSource();refresh();invalidate();};
for(const [id,key]of [['fit-count','fitCount'],['fit-budget','fitBudget']])$(id).onchange=()=>{state[key]=Number($(id).value);if(id==='fit-count')advanced.resetSource();invalidate();};
for(const [id,key]of [['lens-enabled','lensEnabled'],['lens-content','lensContent'],['lens-mode','lensMode'],['lens-radius','lensRadius'],['lens-ior','lensIor'],['lens-dispersion','lensDispersion']])$(id).oninput=()=>{state[key]=$(id).type==='checkbox'?$(id).checked:id==='lens-mode'?$(id).value:Number($(id).value);refreshTools();invalidate();};
let lensDragging=false;$('lens').onpointerdown=e=>{lensDragging=true;$('lens').setPointerCapture(e.pointerId);moveLens(e);};function moveLens(e){if(!lensDragging)return;const r=$('lens').getBoundingClientRect();state.lensX=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));state.lensY=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));invalidate();}$('lens').onpointermove=moveLens;$('lens').onpointerup=$('lens').onpointercancel=()=>lensDragging=false;
$('clear-history').onclick=()=>{clear();invalidate();};$('reset-view').onclick=()=>{state.yaw=.55;state.pitch=.28;state.zoom=3.9;invalidate();};
let dragging=null;const output=$('advanced');output.onpointerdown=e=>{if(!isVolume())return;dragging={x:e.clientX,y:e.clientY};output.setPointerCapture(e.pointerId);};output.onpointermove=e=>{if(!dragging)return;state.yaw+=(e.clientX-dragging.x)*.008;state.pitch=Math.max(-1.4,Math.min(1.4,state.pitch+(e.clientY-dragging.y)*.008));dragging={x:e.clientX,y:e.clientY};invalidate();};output.onpointerup=output.onpointercancel=()=>dragging=null;output.addEventListener('wheel',e=>{if(!isVolume())return;e.preventDefault();state.zoom=Math.max(2.7,Math.min(9,state.zoom*Math.exp(e.deltaY*.001)));invalidate();},{passive:false});
for(const type of ['pointerdown','pointermove','pointerup','pointerleave'])$('source').addEventListener(type,e=>{if(!machine)return;const rect=$('source').getBoundingClientRect(),b=bounds(),scale=Math.min(720/(b.maxX-b.minX),480/(b.maxY-b.minY)),x=((e.clientX-rect.left)/rect.width*720-(720-(b.maxX-b.minX)*scale)/2)/scale+b.minX,y=((e.clientY-rect.top)/rect.height*480-(480-(b.maxY-b.minY)*scale)/2)/scale+b.minY;const method={pointerdown:'pointerDown',pointermove:'pointerMove',pointerup:'pointerUp',pointerleave:'pointerExit'}[type];machine[method]?.(x,y);invalidate();});
function download(blob,base,ext){let i=0;if(!$('overwrite').checked){const key='rivx-effect-export:'+base+ext;try{i=Number(localStorage.getItem(key)||0);localStorage.setItem(key,String(i+1));}catch{i=download.counts[key]||0;download.counts[key]=i+1;}}const name=base+(i?` [${i}]`:'')+ext,url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);return name;}download.counts={};
$('svg').onclick=()=>{try{const name=download(new Blob([effects.svg($('source'),state)],{type:'image/svg+xml'}),'rive-contours','.svg');$('export-status').textContent=`Saved ${name}.`;}catch(e){fail(e);}};
$('riv-snapshot').onclick=()=>{try{if(!Number(document.body.dataset.fitCount))throw Error('Select a fitting mode first, then export its optimized geometry.');const bytes=advanced.packRive($('source'),state,null,sourceCredit?(sourceCredit.credit+' '+(sourceCredit.url||'')):sourceName),name=download(new Blob([bytes]),'layered-splat-snapshot','.riv');$('export-status').textContent=`Saved ${name}: ordinary ellipse shapes, not a custom shader.`;}catch(e){fail(e);}};
async function getText(url){const r=await fetch(url);if(!r.ok)throw Error('Missing export dependency: '+url);return r.text();}
$('export').onclick=async()=>{if(exporting||!sourceBytes)return;exporting=true;const resumePlaying=state.playing,resumeFitting=state.fitRunning;state.playing=false;state.fitRunning=false;refresh();$('export').disabled=true;$('export-status').textContent='Packing source, runtime and captured history…';try{let assets=embedded;if(!assets){const [runtimeSource,effectsSource,advancedSource,fittingSource,lensSource,appSource,css,license,wasm,sample,glassMeta]=await Promise.all([getText('../vector-replay/vendor/webgl2_advanced.js'),getText('effects.js'),getText('advanced.js'),getText('fitting.js'),getText('lens.js'),getText('app.js'),getText('style.css'),getText('../vector-replay/vendor/LICENSE'),fetch('../vector-replay/vendor/rive.wasm').then(r=>r.arrayBuffer()),fetch('kinetic-rosette.riv').then(r=>r.arrayBuffer()),fetch('glass-meta.json').then(r=>r.json())]);assets={runtimeSource,effectsSource,advancedSource,fittingSource,lensSource,appSource,css,license,wasmBase64:encode64(new Uint8Array(wasm)),sampleBase64:encode64(new Uint8Array(sample)),glassMeta};}
 const history=await advanced.snapshot(),machineInputs={};if(machine)for(let i=0;i<machine.inputCount();i++){const input=machine.input(i);if(input.type!==runtime.SMIInput.trigger)machineInputs[input.name]=input.type===runtime.SMIInput.bool?input.asBool().value:input.asNumber().value;}
 const bundle={...assets,format:'RIVX-EFFECT-HYBRID-3',sourceBase64:encode64(sourceBytes),sourceName,sourceMeta,sourceKey,sourceCredit,boardIndex,settings:{...state},animation:$('animation').value,animationTime:anim?.time||0,machineInputs,history,elapsed,officialGpuCanvas:false,nativeRivxCompatible:false};
 const clone=document.documentElement.cloneNode(true);clone.querySelectorAll('script,link[rel="stylesheet"]').forEach(n=>n.remove());clone.querySelector('#error').hidden=true;clone.querySelector('#export').disabled=false;clone.querySelector('#export-status').textContent='Self-contained player: source, runtime, pipeline and captured image history.';clone.querySelector('#status').textContent='Loading bundled official Rive runtime…';clone.querySelector('a[href="gpu-canvas-status.html"]')?.removeAttribute('href');clone.querySelector('.ready-exports')?.remove();clone.querySelector('a[href="credits.html"]')?.removeAttribute('href');const home=clone.querySelector('header a');home.removeAttribute('href');home.textContent='RIVX / exported hybrid study';const style=document.createElement('style');style.textContent=assets.css;clone.querySelector('head').append(style);const json=JSON.stringify(bundle).replace(/</g,'\\u003c'),script=assets.appSource.replace(/<\/script/gi,'<\\/script'),html='<!doctype html>\n'+clone.outerHTML.replace('</body>',`<script>window.__RIVX_EFFECT_BUNDLE__=${json};<\/script><script type="module">${script}<\/script></body>`);const name=download(new Blob([html],{type:'text/html'}),'rive-effect-hybrid','.html');$('export-status').textContent=`Saved ${name} · ${(html.length/1048576).toFixed(1)} MB. Open directly in a browser.`;
 }catch(e){fail(e);$('export-status').textContent='Export failed; original retained.';}finally{exporting=false;state.playing=resumePlaying;state.fitRunning=resumeFitting;refresh();last=0;invalidate();$('export').disabled=false;}};
new IntersectionObserver(e=>{visible=e[0].isIntersecting;last=0;invalidate();}).observe(document.querySelector('.views'));document.addEventListener('visibilitychange',()=>{last=0;invalidate();});window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='portfolio-lab-visibility'){hostPaused=!e.data.visible;last=0;invalidate();}});
async function start(){refresh();runtime=await Rive(embedded?{wasmBinary:decode64(embedded.wasmBase64)}:{locateFile:()=>new URL('../vector-replay/vendor/rive.wasm',import.meta.url).href});renderer=runtime.makeRenderer($('source'),true);if(!renderer)throw Error('Official Rive renderer could not initialize.');effects=makeEffects($('effect'),$('curves'));lens=makeLens($('lens'));advanced=makeAdvanced($('advanced'),$('rive-output'),runtime,(input,d,s)=>effects.segments(input,d,s),makeGaussianFit);const query=new URLSearchParams(location.search),requested=query.get('preset');if(!embedded&&descriptions[requested])state.preset=requested;if(!embedded&&query.get('paused')==='1')state.playing=false;if(!embedded&&['glass','mirror'].includes(query.get('lens'))){state.lensEnabled=true;state.lensMode=query.get('lens');}const initial=query.get('source')||(requested?(['oil','splats','rive-splats','stm'].includes(requested)?'faux':['time','motion','iso'].includes(requested)?'jellyfish':requested==='source'?'rosette':'truck'):'truck');if(!embedded){const presetDefaults=Object.values(showcases).find(v=>v.source===initial&&v.preset===state.preset);if(presetDefaults)Object.assign(state,presetDefaults);}if(embedded){await load(decode64(embedded.sourceBase64),embedded.sourceName,embedded.sourceMeta,{key:embedded.sourceKey||'import',credit:embedded.sourceCredit,artboard:embedded.boardIndex,animation:embedded.animation});}else{if(!requested)Object.assign(state,showcases['truck-beam']);await selectSource(sources[initial]?initial:'truck');if(initial==='faux'&&['splats','rive-splats'].includes(requested)){state.density=60;state.strength=.72;setBoard(10);}else if(requested==='oil')state.strength=1.4;}if(embedded?.animation){$('animation').value=embedded.animation;chooseAnimation(embedded.animation);}if(anim&&embedded?.animationTime)anim.time=embedded.animationTime;if(machine&&embedded?.machineInputs)for(let i=0;i<machine.inputCount();i++){const input=machine.input(i),value=embedded.machineInputs[input.name];if(value!==undefined){const typed=input.type===runtime.SMIInput.bool?input.asBool():input.asNumber();typed.value=value;const control=[...$('machine-inputs').querySelectorAll('input')].find(c=>c.dataset.machineName===input.name);if(control){if(control.type==='checkbox')control.checked=value;else control.value=value;}}}
 if(embedded?.history)await advanced.restore(embedded.history);elapsed=embedded?.elapsed||0;ready=true;controls.forEach(c=>c.disabled=false);$('animation').disabled=!art.animationCount()&&!art.stateMachineCount();refresh();if(embedded){$('glass').disabled=embedded.sourceKey!=='glass';for(const o of $('source-choice').options)o.disabled=!['rosette','import',embedded.sourceKey].includes(o.value);document.querySelectorAll('[data-showcase]').forEach(b=>b.disabled=showcases[b.dataset.showcase].source!==embedded.sourceKey);}invalidate();if(parent!==window)parent.postMessage({type:'portfolio-lab-preview-ready'},location.origin);}
start().catch(fail);window.addEventListener('pagehide',e=>{if(raf)runtime.cancelAnimationFrame(raf);raf=0;if(!e.persisted){ready=false;anim?.delete();machine?.delete();art?.delete();file?.delete();renderer?.delete();effects?.dispose();advanced?.dispose();lens?.dispose();}});window.addEventListener('pageshow',e=>{if(e.persisted){last=0;invalidate();}});
