// A movable image-space optical layer; it does not infer hidden 3D geometry.
export function makeLens(canvas){
 const gl=canvas.getContext('webgl2',{alpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL2 is required for the optical layer.');
 const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const vs=shader(gl.VERTEX_SHADER,`#version 300 es
 void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(p*2.-1.,0,1);}`),fs=shader(gl.FRAGMENT_SHADER,`#version 300 es
 precision highp float;out vec4 color;uniform sampler2D image;uniform vec2 center;uniform float radius,ior,dispersion,mirror,content;
 vec3 sampleAt(vec2 p){return texture(image,clamp(p,vec2(.001),vec2(.999))).rgb;}float lum(vec3 c){return dot(c,vec3(.2126,.7152,.0722));}
 void main(){vec2 p=vec2(gl_FragCoord.x/720.,1.-gl_FragCoord.y/480.);vec3 original=sampleAt(p);vec2 q=(p-center)*vec2(1.5,1.)/radius;float r=length(q);if(r>=1.){color=vec4(original,1);return;}float z=sqrt(max(.001,1.-r*r));vec2 d=vec2(1./720.,1./480.);vec2 gradient=vec2(lum(sampleAt(p+vec2(d.x,0)))-lum(sampleAt(p-vec2(d.x,0))),lum(sampleAt(p+vec2(0,d.y)))-lum(sampleAt(p-vec2(0,d.y))));vec2 normal=q+gradient*content*1.8;float bend=(1.-1./ior)*(.22+.78*z);vec2 shift=normal*radius/vec2(1.5,1.)*bend;vec3 refracted=vec3(sampleAt(p-shift*(1.+dispersion)).r,sampleAt(p-shift).g,sampleAt(p-shift*(1.-dispersion)).b);vec2 reflected=center+vec2(-q.x,q.y)*radius/vec2(1.5,1.)*(.72+.28*z);vec3 reflectedColor=sampleAt(reflected);float fresnel=.035+.7*pow(1.-z,4.);vec3 base=mirror>.5?reflectedColor:mix(refracted,reflectedColor,fresnel);float highlight=pow(max(0.,dot(normalize(vec3(normal,z)),normalize(vec3(-.4,-.65,.8)))),32.);base+=highlight*(mirror>.5?.3:.65)*vec3(.8,.92,1.);float rim=smoothstep(.91,.97,r)*(1.-smoothstep(.985,1.,r));base=mix(base,vec3(.72,.86,.88),rim*.72);color=vec4(mix(original,base,1.-smoothstep(.993,1.,r)),1);}`);
 const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.deleteShader(vs);gl.deleteShader(fs);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 return {draw(input,state){gl.useProgram(program);gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,input);gl.uniform2f(gl.getUniformLocation(program,'center'),state.lensX,state.lensY);for(const [k,v]of Object.entries({radius:state.lensRadius,ior:state.lensIor,dispersion:state.lensDispersion,mirror:state.lensMode==='mirror'?1:0,content:state.lensContent?1:0}))gl.uniform1f(gl.getUniformLocation(program,k),v);gl.viewport(0,0,720,480);gl.drawArrays(gl.TRIANGLES,0,3);},dispose(){gl.deleteTexture(texture);gl.deleteProgram(program);}};
}
