import Rive from '../vector-replay/vendor/webgl2_advanced.js';
import {createRenderer} from './renderer.js';import {marks} from './marks.js';
const $=id=>document.getElementById(id),state={degrees:0,roughness:.24,ior:1.5,playing:false,vectors:true,regions:false},layers=[];
let scene,runtime,shader,retained,ready=false,raf=0,last=0,visible=true,hostPaused=false,dirty=true,yaw,frames=0;
const ART={minX:0,minY:0,maxX:640,maxY:420};
const controls=[...document.querySelectorAll('input,button')];controls.forEach(control=>control.disabled=true);
async function riveLayer(id,url){const canvas=$(id),renderer=runtime.makeRenderer(canvas);if(!renderer)throw Error('Rive could not initialize '+id);const response=await fetch(url);if(!response.ok)throw Error('Missing Rive asset: '+url);const file=await runtime.load(new Uint8Array(await response.arrayBuffer()));if(!file)throw Error('Rive rejected '+url);const art=file.defaultArtboard();if(!art)throw Error('No artboard in '+url);const nodes=Array.from({length:171},(_,j)=>art.node('mark'+j));if(nodes.some(x=>!x))throw Error('Incomplete semantic Rive marks');const anim=id==='portable'?new runtime.LinearAnimationInstance(art.animationByIndex(0),art):null;const layer={canvas,renderer,file,art,nodes,anim};layers.push(layer);return layer;}
function drawRive(layer,retainedView=false){const {canvas,renderer,art,nodes,anim}=layer;if(anim){anim.time=(state.degrees+100)/200;anim.apply(1);}else{const geometry=marks(scene,state.degrees,retainedView?yaw:scene.camera.yaw);geometry.forEach((m,i)=>{const n=nodes[i],dx=m.b[0]-m.a[0],dy=m.b[1]-m.a[1];n.x=m.a[0];n.y=m.a[1];n.rotation=Math.atan2(dy,dx);n.scaleX=Math.hypot(dx,dy);n.scaleY=state.vectors?m.width:0;});}
if(anim&&!state.vectors)nodes.forEach(n=>n.scaleY=0);art.advance(0);renderer.clear();renderer.save();renderer.align(runtime.Fit.contain,runtime.Alignment.center,{minX:0,minY:0,maxX:canvas.width,maxY:canvas.height},ART);art.draw(renderer);renderer.restore();renderer.flush();canvas.dataset.renderer='official-rive-webgl2';}
function render(){shader.draw({...state,viewMode:state.regions?1:0});retained.draw({...state,yaw,viewMode:state.regions?1:0});layers.forEach((l,i)=>drawRive(l,i===2));$('angle-value').textContent=state.degrees.toFixed(1)+'°';const sample=Math.min(24,Math.floor((state.degrees+100)/200*24+1e-6));$('portable-status').textContent=`Official .riv · pose ${sample+1}/25 · ${(-100+sample*200/24).toFixed(1)}°`; $('shader-status').textContent=`Live shader · ${state.degrees.toFixed(1)}° · fixed camera`;$('retained-status').textContent=`Live scene · view ${((yaw-scene.camera.yaw)*180/Math.PI).toFixed(1)}° from bake`;document.body.dataset.frames=String(++frames);document.body.dataset.light=String(state.degrees);document.body.dataset.yaw=String(yaw);dirty=false;}
function wake(){if(ready&&!raf&&visible&&!hostPaused&&!document.hidden)raf=runtime.requestAnimationFrame(tick);}
function tick(t){raf=0;if(!visible||hostPaused||document.hidden){last=0;return;}const dt=last?Math.min(.05,(t-last)/1000):0;last=t;if(state.playing){state.degrees+=dt*22;if(state.degrees>100)state.degrees=-100;$('angle').value=String(state.degrees);dirty=true;}if(dirty)render();if(state.playing)wake();}
function update(){dirty=true;wake();}
for(const key of ['angle','roughness','ior'])$(key).addEventListener('input',()=>{state[key==='angle'?'degrees':key]=Number($(key).value);if(key==='angle'){state.playing=false;$('play').textContent='Animate light';}update();});
for(const key of ['vectors','regions'])$(key).addEventListener('change',()=>{state[key]=$(key).checked;update();});
$('play').onclick=()=>{state.playing=!state.playing;last=0;$('play').textContent=state.playing?'Pause light':'Animate light';update();};
$('reset').onclick=()=>{Object.assign(state,{degrees:0,roughness:.24,ior:1.5,playing:false,regions:false,vectors:true});yaw=scene.camera.yaw;$('angle').value=0;$('roughness').value=.24;$('ior').value=1.5;$('regions').checked=false;$('vectors').checked=true;$('play').textContent='Animate light';update();};
let drag=null;$('retained').onpointerdown=e=>{drag=e.clientX;$('retained').setPointerCapture(e.pointerId);};$('retained').onpointermove=e=>{if(drag===null)return;yaw-=(e.clientX-drag)*.008;drag=e.clientX;update();};$('retained').onpointerup=$('retained').onpointercancel=()=>drag=null;
$('retained').onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();yaw+=(e.key==='ArrowRight'?.12:-.12);update();}};
$('save-scene').onclick=()=>{const blob=new Blob([JSON.stringify({...scene,controls:{...state,yaw}},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='glass-relighting-study.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;last=0;wake();}).observe(document.querySelector('.panes'));document.addEventListener('visibilitychange',()=>{last=0;wake();});window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.type==='portfolio-lab-visibility'){hostPaused=!e.data.visible;last=0;wake();}});
async function start(){scene=await (await fetch('./scene.json')).json();yaw=scene.camera.yaw;shader=createRenderer($('shader'),scene);retained=createRenderer($('retained'),scene);runtime=await Rive({locateFile:()=>new URL('../vector-replay/vendor/rive.wasm',import.meta.url).href});await riveLayer('portable','glass-light.riv');await riveLayer('shader-vectors','semantic-overlay.riv');await riveLayer('retained-vectors','semantic-overlay.riv');ready=true;controls.forEach(control=>control.disabled=false);render();if(parent!==window)parent.postMessage({type:'portfolio-lab-preview-ready'},location.origin);wake();}
start().catch(e=>{$('error').hidden=false;$('error').textContent='The comparison could not start: '+e.message;document.body.dataset.error=e.message;console.error(e);});
window.addEventListener('pagehide',e=>{if(raf)runtime.cancelAnimationFrame(raf);raf=0;if(!e.persisted){ready=false;layers.forEach(l=>{l.anim?.delete();l.art.delete();l.file.delete();l.renderer.delete();});shader?.dispose();retained?.dispose();}});window.addEventListener('pageshow',()=>{last=0;update();});
