import {crispPresentation} from '../presentation.js';
import {createModalAudio} from '../modal-audio.js';
import {createShaderView} from './driver.js';
import {eigenField,handleModalGesture,updateModalDrag,advanceModalClock,updateModalInterface} from './modal-host.js';
import {hasMaterialControls,makeControlState,updateControlSkin} from './control-skin.js?v=20260921-finish';
const pieces={
 'material-nocturne':{title:'Material nocturne',machine:'Instrument',defaults:{roughness:.32,strength:.8,light:.2,playing:1,view:0,controlStyle:2},note:'Analytic materials, finite area-light quadrature and approximate studio reflections. The gold Rive plot shows the shared roughness model.'},
 'spectral-observatory':{title:'Spectral observatory',machine:'Instrument',defaults:{roughness:.32,strength:.75,light:.2,playing:1,view:0,controlStyle:3},note:'Seven wavelength bands and analytic optical boundaries, with approximate receiver and atmospheric terms. Both native graphs use the same wavelength/index equation.'},
 'resonant-membrane':{title:'Resonant membrane',machine:'Membrane',defaults:{n:2,m:3,mix:.72,amplitude:.26,playing:1,controlStyle:2,excitationMode:0,strikeTime:0,strikeX:.37,strikeY:.41,strikeSerial:0,damping:.18,fundamental:110,audioEnabled:0},note:'Fixed-edge membrane eigenmodes and a nine-mode struck response. Position, modal weights and decay drive the GPU surface, native Rive diagrams and optional Web Audio synthesis; the visual phase is deliberately slowed.'},
 'interactive-optics':{title:'Liquid optics',machine:'Instrument',defaults:{lensX:490,lensY:310,power:1.05,dispersion:1.1,frost:.12,mode:0,playing:1},note:'Stylized image-space optical sampling with RGB separation and deterministic blur. Drag the actual lens or the native slider tracks in either route.'}
};
const $=id=>document.getElementById(id),linked=$('linked'),status=$('status'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const detail=crispPresentation($('crisp-details'),[$('leftStage'),$('rightStage')]);
let slug='spectral-observatory',piece=pieces[slug],views={left:null,right:null},shader=null,controlShader=null,controlState=makeControlState(),raf=0,generation=0,loading=[],audio=[],audioSide='left',lastTime=0,rightTime=0,phaseClock=0,phaseStarted=false,phaseWasPlaying=true,previous={left:null,right:null},diagramKey='',nodeCount=0,hostPaused=false,visible=true,drag=null,rightHover=0;
const number=(view,key)=>view?.viewModelInstance?.number(key),put=(view,key,value)=>{const p=number(view,key);if(p&&p.value!==value)p.value=value;},label=(key,value)=>{const p=views.right?.viewModelInstance?.string(key);if(p&&p.value!==value)p.value=value;};
const values=view=>Object.fromEntries(Object.entries(piece.defaults).map(([k,v])=>[k,number(view,k)?.value??v]));
const changed=(a,b)=>b&&Object.keys(piece.defaults).some(k=>k!=='strikeTime'&&Math.abs(a[k]-b[k])>1e-6);
const write=(view,v)=>{for(const k of Object.keys(piece.defaults))put(view,k,v[k]);};
function resize(){for(const v of Object.values(views))v?.resizeDrawingSurfaceToCanvas(Math.min(devicePixelRatio||1,2));}
function error(side,e,token=generation){if(token!==generation)return;$(side+'Loading').hidden=false;$(side+'Loading').textContent=String(e.message||e)+' Use Restart to retry.';status.textContent='A route needs attention';console.error(e);}
function load(side,src,gpu,token){return new Promise((resolve,reject)=>{
 const view=new rive.Rive({src:src+'?v=20260921-finish',canvas:$(side),autoplay:true,autoBind:true,enableGPUCanvas:gpu,stateMachine:piece.machine,layout:new rive.Layout({fit:rive.Fit.Contain,alignment:rive.Alignment.Center}),
 onLoad(){if(token!==generation){view.cleanup();resolve(null);return;}views[side]=view;resize();if(reduced)put(view,'playing',0);resolve(view);},
 onAdvance(e){if(side!=='left'||slug!=='resonant-membrane'||token!==generation)return;const text=view.viewModelInstance?.string('readout')?.value||'';if(!text||text.startsWith('Initializing'))return;const play=(number(view,'playing')?.value??1)>.5;if(!phaseStarted){phaseStarted=true;phaseClock=0;phaseWasPlaying=play;return;}if(play&&phaseWasPlaying)phaseClock+=Number(e.data||0)*Math.PI/2;phaseWasPlaying=play;},
 onLoadError(e){reject(new Error(e.data||'Could not load '+src));}});loading.push(view);
});}
function leftClock(){return slug==='resonant-membrane'?phaseClock:(number(views.left,'time')?.value||0);}
function eigen(x,y,v){return eigenField(x,y,v);}
function nodalSegments(v){const result=[],cells=v.excitationMode>.5?28:44,eps=.00001;for(let y=0;y<cells;y++)for(let x=0;x<cells;x++){const p=[[(x+eps)/cells,(y+eps)/cells],[(x+1-eps)/cells,(y+eps)/cells],[(x+1-eps)/cells,(y+1-eps)/cells],[(x+eps)/cells,(y+1-eps)/cells]],crossings=[];for(let k=0;k<4;k++){const a=p[k],b=p[(k+1)%4],fa=eigen(...a,v),fb=eigen(...b,v);if(fa*fb<0){const t=fa/(fa-fb);crossings.push([1176+(a[0]+(b[0]-a[0])*t)*144,266+(a[1]+(b[1]-a[1])*t)*144]);}}if(crossings.length>=2)result.push([crossings[0],crossings[1]]);if(crossings.length===4)result.push([crossings[2],crossings[3]]);}return result;}
function updateInterface(v,time,dt){
 const view=views.right;if(!view)return;put(view,'time',time);
 if(slug==='interactive-optics'){
  const names=['power','dispersion','frost'];for(let i=0;i<3;i++){const k=names[i],t=v[k]/(i<2?2:1);put(view,k+'X',1140+t*224);put(view,k+'Width',Math.max(1,t*224));label(k+'Text',i===2?Math.round(v[k]*100)+'%':v[k].toFixed(2));}
  put(view,'guideX',36+v.lensX);put(view,'guideY',168+v.lensY);put(view,'playOn',v.playing);put(view,'playOff',1-v.playing);put(view,'grabbed',drag?.kind==='lens'?1:0);put(view,'lensHover',rightHover);label('motionText',v.playing>.5?'Hold motion':'Resume motion');label('readout',`X ${Math.floor(v.lensX)}   Y ${Math.floor(v.lensY)}`);
  for(let c=0;c<3;c++){put(view,'mode'+c,Math.abs(v.mode-c)<.1?1:0);put(view,'hover'+c,number(view,'hoverTarget'+c)?.value||0);for(let i=0;i<=64;i++){const t=i/64,y=322-Math.sin(t*Math.PI)*v.power*23+(c-1)*v.dispersion*6*Math.sin(t*Math.PI)+(v.mode>1.5?Math.sin(t*Math.PI*3+time)*4:0);put(view,`optical${c}Y${i}`,y);}}
 }else if(slug==='resonant-membrane'){
  updateModalInterface(v,(k,x)=>put(view,k,x),label,controlState.pointer);
  const signature=[v.n,v.m,v.mix,v.excitationMode,v.strikeX,v.strikeY,v.damping,v.excitationMode>.5?Math.floor(v.strikeTime*8):0].join('/');if(signature!==diagramKey){const segments=nodalSegments(v);if(segments.length>1024)throw Error('Native nodal pool exhausted');for(let i=0;i<Math.max(nodeCount,segments.length);i++)for(let j=0;j<2;j++){const p=segments[i]?.[j]||[1176,266];put(view,`node${i}X${j}`,p[0]);put(view,`node${i}Y${j}`,p[1]);}nodeCount=segments.length;diagramKey=signature;}
  const omega=Math.sqrt(v.n*v.n+v.m*v.m)/Math.sqrt(13);for(let i=0;i<=180;i++)put(view,'traceY'+i,758+(v.excitationMode>.5?eigenField(.43,.57,v,Math.max(0,v.strikeTime-i/180*2))*v.amplitude*75:Math.cos(time*omega-i/180*Math.PI*4)*v.amplitude*44));
  label('readout',v.excitationMode>.5?`STRIKE ${v.strikeTime.toFixed(2)} s · 9 MODES`:`(${v.n},${v.m}) + ${v.mix.toFixed(2)} (${v.m},${v.n})  ${v.playing>.5?'LIVE':'HELD'}`);[(v.n-2)/5,v.mix,(v.amplitude-.05)/.45].forEach((t,i)=>put(view,'sliderX'+i,1124+t*256));
 }else{
  put(view,'lightMarker',1124+(v.light+1)*128);label('readout',`ROUGH ${v.roughness.toFixed(2)}  ${slug==='spectral-observatory'?'DISP':'COAT'} ${v.strength.toFixed(2)}`);
  const key=[v.roughness,v.strength].join('/');if(key!==diagramKey){for(let layer=0;layer<2;layer++)for(let i=0;i<=128;i++){const t=i/128;let y;if(slug==='spectral-observatory'){const d=layer===0?v.strength:.4,index=1.47+d*.075*((550/(400+300*t))**2-.46);y=(index-1.46)*800;}else{const a=layer===0?Math.max(.07,v.roughness):.22,c=Math.cos((t-.5)*Math.PI),d=(a*a-1)*c*c+1;y=105*a**4/(d*d);}put(view,`plot${layer}Y${i}`,396-clamp(y,0,112));}diagramKey=key;}[(v.roughness-.04)/.76,v.strength,(v.light+1)*.5].forEach((t,i)=>put(view,'sliderX'+i,1124+t*256));
 }
}
function tick(now){raf=0;if(document.hidden||hostPaused||!visible)return;const dt=lastTime?Math.min(.1,(now-lastTime)/1000):0;lastTime=now;
 if(!views.left||!views.right||!shader)return;let left=values(views.left),right=values(views.right);
 if(linked.checked){if(changed(right,previous.right)&&!changed(left,previous.left)){write(views.left,right);left=right;}else{write(views.right,left);right=left;}rightTime=leftClock();}else if(right.playing>.5)rightTime+=dt*(slug==='resonant-membrane'?Math.PI/2:1);
 if(slug==='resonant-membrane'&&!linked.checked){right.strikeTime=advanceModalClock(right,dt,previous.right?.strikeSerial);put(views.right,'strikeTime',right.strikeTime);}
 previous={left:{...left},right:{...right}};updateInterface(right,rightTime,dt);if(controlShader)controlShader.render({uniforms:updateControlSkin(controlState,slug,right,dt,drag,(k,v)=>put(views.right,k,v),label)});shader.render({...right,time:rightTime,lensHover:linked.checked&&!drag?(number(views.left,'lensHover')?.value||rightHover):rightHover,grabbed:drag?.kind==='lens'?1:(number(views.left,'grabbed')?.value||0)});for(const a of audio)a.update();raf=requestAnimationFrame(tick);
}
function syncVisibility(){const show=!document.hidden&&!hostPaused&&visible;for(const v of Object.values(views))show?v?.play():v?.pause();if(!show){cancelAnimationFrame(raf);raf=0;}else if(!raf&&shader)raf=requestAnimationFrame(tick);lastTime=0;}
function release(){for(const a of audio)a.dispose();audio=[];cancelAnimationFrame(raf);raf=0;shader?.dispose();shader=null;controlShader?.dispose();controlShader=null;for(const v of loading)v.cleanup();loading=[];views={left:null,right:null};}
async function openPiece(next){if(!pieces[next])next='spectral-observatory';const token=++generation;release();slug=next;piece=pieces[slug];detail.select(slug==='resonant-membrane');controlState=makeControlState();$('externalControls').hidden=!hasMaterialControls(slug);rightTime=phaseClock=0;phaseStarted=false;phaseWasPlaying=true;previous={left:null,right:null};diagramKey='';nodeCount=0;drag=null;rightHover=0;lastTime=0;history.replaceState(null,'','#'+slug);document.querySelectorAll('[data-piece]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.piece===slug)));$('model-note').textContent=piece.note;status.textContent='Loading '+piece.title+'…';for(const side of ['left','right']){$(side+'Loading').hidden=false;$(side+'Loading').textContent='Loading '+(side==='left'?'signed document':'ordinary Rive + WebGPU')+'…';}
 await Promise.all([load('left','../exports/'+slug+'.riv',true,token).then(()=>{if(token===generation)$('leftLoading').hidden=true;}).catch(e=>error('left',e,token)),Promise.all([load('right','interfaces/'+slug+'.riv',false,token),hasMaterialControls(slug)?createShaderView($('externalControls'),{shaderUrl:'runtime/control_skin.wgsl',scene:'control-skin',width:294,height:450,transparent:true,onError:e=>error('right',e,token)}).then(v=>{if(token!==generation)v.dispose();else controlShader=v;}):Promise.resolve(),createShaderView($('external'),{shaderUrl:'runtime/'+slug+'.wgsl',scene:slug,onError:e=>error('right',e,token)}).then(v=>{if(token!==generation)v.dispose();else shader=v;})]).then(()=>{if(token===generation)$('rightLoading').hidden=true;}).catch(e=>error('right',e,token))]);
 if(token===generation&&views.left&&views.right&&shader){status.textContent=piece.title+' · both routes ready';if(slug==='resonant-membrane')audio=[createModalAudio(document.querySelector('.compare-grid'),()=>values(views[linked.checked?'left':audioSide]),message=>status.textContent=piece.title+' · '+message)];syncVisibility();if(parent!==window)parent.postMessage({type:'portfolio-lab-preview-ready'},location.origin);}
}
function point(e){const b=$('right').getBoundingClientRect();return{x:(e.clientX-b.left)*1440/b.width,y:(e.clientY-b.top)*940/b.height};}
function slide(x){const t=clamp((x-(slug==='interactive-optics'?1140:1124))/(slug==='interactive-optics'?224:256),0,1),i=drag.index;if(slug==='interactive-optics')put(views.right,['power','dispersion','frost'][i],t*(i<2?2:1));else if(slug==='resonant-membrane'){if(i<2)put(views.right,'excitationMode',0);if(i===0){const n=Math.round(2+t*5);put(views.right,'n',n);put(views.right,'m',n+1);}else put(views.right,i===1?'mix':'amplitude',i===1?t:.05+t*.45);}else put(views.right,['roughness','strength','light'][i],i===0?.04+t*.76:i===1?t:t*2-1);}
$('right').addEventListener('pointerdown',e=>{const p=point(e);if(slug==='resonant-membrane'){const handled=handleModalGesture(p,values(views.right),(k,v)=>put(views.right,k,v));if(handled){if(typeof handled==='string'){drag={kind:'modal-slider',key:handled};$('right').setPointerCapture(e.pointerId);}return;}}const ys=slug==='interactive-optics'?[434,522,610]:[529,615,705];if(p.x>=1109&&p.x<=1395){const i=ys.findIndex(y=>Math.abs(p.y-y)<18);if(i>=0){drag={kind:'slider',index:i};slide(p.x);$('right').setPointerCapture(e.pointerId);return;}}if(slug==='interactive-optics'){const v=values(views.right);if(Math.abs(p.x-36-v.lensX)<207&&Math.abs(p.y-168-v.lensY)<145){drag={kind:'lens',dx:p.x-36-v.lensX,dy:p.y-168-v.lensY};$('right').setPointerCapture(e.pointerId);}}});
$('right').addEventListener('pointermove',e=>{const p=point(e),v=values(views.right);controlState.pointer=p;if(drag?.kind==='modal-slider'){updateModalDrag(drag.key,p,v,(k,x)=>put(views.right,k,x));return;}rightHover=slug==='interactive-optics'&&Math.abs(p.x-36-v.lensX)<207&&Math.abs(p.y-168-v.lensY)<145?1:0;if(drag?.kind==='slider')slide(p.x);if(drag?.kind==='lens'){put(views.right,'lensX',clamp(p.x-36-drag.dx,216,824));put(views.right,'lensY',clamp(p.y-168-drag.dy,154,486));}});
for(const type of ['pointerup','pointercancel'])$('right').addEventListener(type,()=>drag=null);$('right').addEventListener('pointerleave',()=>{if(!drag){rightHover=0;controlState.pointer={x:-100,y:-100};}});
for(const side of ['left','right'])$(side).addEventListener('pointerdown',()=>audioSide=side,true);
$('restart').addEventListener('click',()=>openPiece(slug));document.querySelectorAll('[data-piece]').forEach(b=>b.addEventListener('click',()=>openPiece(b.dataset.piece)));document.addEventListener('visibilitychange',syncVisibility);window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='portfolio-lab-visibility'){hostPaused=!e.data.visible;syncVisibility();}});new IntersectionObserver(e=>{visible=e[0].isIntersecting;syncVisibility();}).observe(document.querySelector('.compare-grid'));new ResizeObserver(resize).observe(document.querySelector('.compare-grid'));window.addEventListener('pagehide',()=>{generation++;release();},{once:true});
const rightControlStyle=()=>({value:number(views.right,'controlStyle')?.value,menu:controlState.open,spring:controlState.spring,shader:!!controlShader});
window.comparisonState=()=>({slug,left:values(views.left),right:values(views.right),leftTime:leftClock(),rightTime,ready:!!(views.left&&views.right&&shader),audio:audio.map(a=>a.state),linked:linked.checked,nodeCount,controlStyle:rightControlStyle(),phaseSource:slug==='resonant-membrane'?'official runtime advance events':'Rive view-model clock'});
rive.RuntimeLoader.setWasmUrl(new URL('../vendor/rive.wasm',location.href).href);openPiece(location.hash.slice(1)||new URLSearchParams(location.search).get('piece')||'spectral-observatory');
